/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import io.ycvk.acorn.api.models.CaptureAccepted
import io.ycvk.acorn.api.models.ErrorResponse

import com.squareup.moshi.Json

import io.ycvk.acorn.api.infrastructure.ApiClient
import io.ycvk.acorn.api.infrastructure.ApiResponse
import io.ycvk.acorn.api.infrastructure.ClientException
import io.ycvk.acorn.api.infrastructure.ClientError
import io.ycvk.acorn.api.infrastructure.ServerException
import io.ycvk.acorn.api.infrastructure.ServerError
import io.ycvk.acorn.api.infrastructure.MultiValueMap
import io.ycvk.acorn.api.infrastructure.PartConfig
import io.ycvk.acorn.api.infrastructure.RequestConfig
import io.ycvk.acorn.api.infrastructure.RequestMethod
import io.ycvk.acorn.api.infrastructure.ResponseType
import io.ycvk.acorn.api.infrastructure.Success
import io.ycvk.acorn.api.infrastructure.toMultiValue

open class CapturesApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "http://127.0.0.1:8080")
        }
    }

    /**
     * POST /v1/captures
     * Hand the agent something shared from the phone
     * Starts a run in a new thread whose input (role &#x60;capture&#x60;) lists the shared subject, text and image. An image is stored under &#x60;attachments/&#x60; in the storage directory before the run starts. Text or an image is required. 
     * @param text Shared text, often a link, plus the owner&#39;s note. (optional)
     * @param subject Title the sharing app gave, such as a page title. (optional)
     * @param image JPEG, PNG, WebP or GIF, at most 10 MiB. (optional)
     * @return CaptureAccepted
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clientCreateCapture(text: kotlin.String? = null, subject: kotlin.String? = null, image: java.io.File? = null) : CaptureAccepted {
        val localVarResponse = clientCreateCaptureWithHttpInfo(text = text, subject = subject, image = image)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CaptureAccepted
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/captures
     * Hand the agent something shared from the phone
     * Starts a run in a new thread whose input (role &#x60;capture&#x60;) lists the shared subject, text and image. An image is stored under &#x60;attachments/&#x60; in the storage directory before the run starts. Text or an image is required. 
     * @param text Shared text, often a link, plus the owner&#39;s note. (optional)
     * @param subject Title the sharing app gave, such as a page title. (optional)
     * @param image JPEG, PNG, WebP or GIF, at most 10 MiB. (optional)
     * @return ApiResponse<CaptureAccepted?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clientCreateCaptureWithHttpInfo(text: kotlin.String?, subject: kotlin.String?, image: java.io.File?) : ApiResponse<CaptureAccepted?> {
        val localVariableConfig = clientCreateCaptureRequestConfig(text = text, subject = subject, image = image)

        return request<Map<String, PartConfig<*>>, CaptureAccepted>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clientCreateCapture
     *
     * @param text Shared text, often a link, plus the owner&#39;s note. (optional)
     * @param subject Title the sharing app gave, such as a page title. (optional)
     * @param image JPEG, PNG, WebP or GIF, at most 10 MiB. (optional)
     * @return RequestConfig
     */
    fun clientCreateCaptureRequestConfig(text: kotlin.String?, subject: kotlin.String?, image: java.io.File?) : RequestConfig<Map<String, PartConfig<*>>> {
        val localVariableBody = mapOf(
            "text" to PartConfig(body = text, headers = mutableMapOf()),
            "subject" to PartConfig(body = subject, headers = mutableMapOf()),
            "image" to PartConfig(body = image, headers = mutableMapOf()),)
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf("Content-Type" to "multipart/form-data")
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/captures",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
