/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import io.ycvk.acorn.api.models.CreateMessageRequest
import io.ycvk.acorn.api.models.CreateRunRequest
import io.ycvk.acorn.api.models.CreateThreadRequest
import io.ycvk.acorn.api.models.DecidePendingActionRequest
import io.ycvk.acorn.api.models.ErrorResponse
import io.ycvk.acorn.api.models.InboxResponse
import io.ycvk.acorn.api.models.InterruptRunResponse
import io.ycvk.acorn.api.models.Message
import io.ycvk.acorn.api.models.MessageListResponse
import io.ycvk.acorn.api.models.PendingActionDecision
import io.ycvk.acorn.api.models.PendingActionDetail
import io.ycvk.acorn.api.models.PendingActionListResponse
import io.ycvk.acorn.api.models.Run
import io.ycvk.acorn.api.models.RunDetail
import io.ycvk.acorn.api.models.RunEvent
import io.ycvk.acorn.api.models.RunResult
import io.ycvk.acorn.api.models.SystemStatus
import io.ycvk.acorn.api.models.Thread
import io.ycvk.acorn.api.models.ThreadListResponse
import io.ycvk.acorn.api.models.ToolListResponse
import io.ycvk.acorn.api.models.UpdateThreadRequest

import com.squareup.moshi.Json

import io.ycvk.acorn.api.infrastructure.ApiClient
import io.ycvk.acorn.api.infrastructure.ApiResponse
import io.ycvk.acorn.api.infrastructure.ClientException
import io.ycvk.acorn.api.infrastructure.ClientError
import io.ycvk.acorn.api.infrastructure.ServerException
import io.ycvk.acorn.api.infrastructure.ServerError
import io.ycvk.acorn.api.infrastructure.MultiValueMap
import io.ycvk.acorn.api.infrastructure.PartConfig
import io.ycvk.acorn.api.infrastructure.RequestConfig
import io.ycvk.acorn.api.infrastructure.RequestMethod
import io.ycvk.acorn.api.infrastructure.ResponseType
import io.ycvk.acorn.api.infrastructure.Success
import io.ycvk.acorn.api.infrastructure.toMultiValue

open class ClientApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "http://127.0.0.1:8080")
        }
    }

    /**
     * POST /v1/threads/{thread_id}/messages
     * Append a user message without starting a run
     * 
     * @param threadId 
     * @param createMessageRequest 
     * @return Message
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clientCreateMessage(threadId: kotlin.String, createMessageRequest: CreateMessageRequest) : Message {
        val localVarResponse = clientCreateMessageWithHttpInfo(threadId = threadId, createMessageRequest = createMessageRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Message
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/threads/{thread_id}/messages
     * Append a user message without starting a run
     * 
     * @param threadId 
     * @param createMessageRequest 
     * @return ApiResponse<Message?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clientCreateMessageWithHttpInfo(threadId: kotlin.String, createMessageRequest: CreateMessageRequest) : ApiResponse<Message?> {
        val localVariableConfig = clientCreateMessageRequestConfig(threadId = threadId, createMessageRequest = createMessageRequest)

        return request<CreateMessageRequest, Message>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clientCreateMessage
     *
     * @param threadId 
     * @param createMessageRequest 
     * @return RequestConfig
     */
    fun clientCreateMessageRequestConfig(threadId: kotlin.String, createMessageRequest: CreateMessageRequest) : RequestConfig<CreateMessageRequest> {
        val localVariableBody = createMessageRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/threads/{thread_id}/messages".replace("{"+"thread_id"+"}", encodeURIComponent(threadId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/threads/{thread_id}/runs
     * Start a runtime run; with input set, record the user message and run in one step (otherwise run the latest unbound user message)
     * 
     * @param threadId 
     * @param createRunRequest  (optional)
     * @return Run
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clientCreateRun(threadId: kotlin.String, createRunRequest: CreateRunRequest? = null) : Run {
        val localVarResponse = clientCreateRunWithHttpInfo(threadId = threadId, createRunRequest = createRunRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Run
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/threads/{thread_id}/runs
     * Start a runtime run; with input set, record the user message and run in one step (otherwise run the latest unbound user message)
     * 
     * @param threadId 
     * @param createRunRequest  (optional)
     * @return ApiResponse<Run?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clientCreateRunWithHttpInfo(threadId: kotlin.String, createRunRequest: CreateRunRequest?) : ApiResponse<Run?> {
        val localVariableConfig = clientCreateRunRequestConfig(threadId = threadId, createRunRequest = createRunRequest)

        return request<CreateRunRequest, Run>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clientCreateRun
     *
     * @param threadId 
     * @param createRunRequest  (optional)
     * @return RequestConfig
     */
    fun clientCreateRunRequestConfig(threadId: kotlin.String, createRunRequest: CreateRunRequest?) : RequestConfig<CreateRunRequest> {
        val localVariableBody = createRunRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/threads/{thread_id}/runs".replace("{"+"thread_id"+"}", encodeURIComponent(threadId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/threads
     * Create a client thread
     * 
     * @param createThreadRequest  (optional)
     * @return Thread
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clientCreateThread(createThreadRequest: CreateThreadRequest? = null) : Thread {
        val localVarResponse = clientCreateThreadWithHttpInfo(createThreadRequest = createThreadRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Thread
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/threads
     * Create a client thread
     * 
     * @param createThreadRequest  (optional)
     * @return ApiResponse<Thread?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clientCreateThreadWithHttpInfo(createThreadRequest: CreateThreadRequest?) : ApiResponse<Thread?> {
        val localVariableConfig = clientCreateThreadRequestConfig(createThreadRequest = createThreadRequest)

        return request<CreateThreadRequest, Thread>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clientCreateThread
     *
     * @param createThreadRequest  (optional)
     * @return RequestConfig
     */
    fun clientCreateThreadRequestConfig(createThreadRequest: CreateThreadRequest?) : RequestConfig<CreateThreadRequest> {
        val localVariableBody = createThreadRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/threads",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/pending-actions/{action_id}:decide
     * Decide a pending client action
     * 
     * @param actionId 
     * @param decidePendingActionRequest 
     * @return PendingActionDecision
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clientDecidePendingAction(actionId: kotlin.String, decidePendingActionRequest: DecidePendingActionRequest) : PendingActionDecision {
        val localVarResponse = clientDecidePendingActionWithHttpInfo(actionId = actionId, decidePendingActionRequest = decidePendingActionRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as PendingActionDecision
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/pending-actions/{action_id}:decide
     * Decide a pending client action
     * 
     * @param actionId 
     * @param decidePendingActionRequest 
     * @return ApiResponse<PendingActionDecision?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clientDecidePendingActionWithHttpInfo(actionId: kotlin.String, decidePendingActionRequest: DecidePendingActionRequest) : ApiResponse<PendingActionDecision?> {
        val localVariableConfig = clientDecidePendingActionRequestConfig(actionId = actionId, decidePendingActionRequest = decidePendingActionRequest)

        return request<DecidePendingActionRequest, PendingActionDecision>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clientDecidePendingAction
     *
     * @param actionId 
     * @param decidePendingActionRequest 
     * @return RequestConfig
     */
    fun clientDecidePendingActionRequestConfig(actionId: kotlin.String, decidePendingActionRequest: DecidePendingActionRequest) : RequestConfig<DecidePendingActionRequest> {
        val localVariableBody = decidePendingActionRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/pending-actions/{action_id}:decide".replace("{"+"action_id"+"}", encodeURIComponent(actionId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /v1/threads/{thread_id}
     * Delete a client thread
     * 
     * @param threadId 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clientDeleteThread(threadId: kotlin.String) : Unit {
        val localVarResponse = clientDeleteThreadWithHttpInfo(threadId = threadId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /v1/threads/{thread_id}
     * Delete a client thread
     * 
     * @param threadId 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun clientDeleteThreadWithHttpInfo(threadId: kotlin.String) : ApiResponse<Unit?> {
        val localVariableConfig = clientDeleteThreadRequestConfig(threadId = threadId)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clientDeleteThread
     *
     * @param threadId 
     * @return RequestConfig
     */
    fun clientDeleteThreadRequestConfig(threadId: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/v1/threads/{thread_id}".replace("{"+"thread_id"+"}", encodeURIComponent(threadId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/inbox
     * Load the mobile inbox aggregate
     * Returns one mobile-friendly attention aggregate over durable backend facts: pending actions, active runs, recent terminal runs, and system readiness. This endpoint does not replace source endpoints and does not introduce a second RunEvent store. 
     * @return InboxResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clientGetInbox() : InboxResponse {
        val localVarResponse = clientGetInboxWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as InboxResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/inbox
     * Load the mobile inbox aggregate
     * Returns one mobile-friendly attention aggregate over durable backend facts: pending actions, active runs, recent terminal runs, and system readiness. This endpoint does not replace source endpoints and does not introduce a second RunEvent store. 
     * @return ApiResponse<InboxResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clientGetInboxWithHttpInfo() : ApiResponse<InboxResponse?> {
        val localVariableConfig = clientGetInboxRequestConfig()

        return request<Unit, InboxResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clientGetInbox
     *
     * @return RequestConfig
     */
    fun clientGetInboxRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/inbox",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/pending-actions/{action_id}
     * Load an actionable pending client action
     * 
     * @param actionId 
     * @return PendingActionDetail
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clientGetPendingAction(actionId: kotlin.String) : PendingActionDetail {
        val localVarResponse = clientGetPendingActionWithHttpInfo(actionId = actionId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as PendingActionDetail
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/pending-actions/{action_id}
     * Load an actionable pending client action
     * 
     * @param actionId 
     * @return ApiResponse<PendingActionDetail?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clientGetPendingActionWithHttpInfo(actionId: kotlin.String) : ApiResponse<PendingActionDetail?> {
        val localVariableConfig = clientGetPendingActionRequestConfig(actionId = actionId)

        return request<Unit, PendingActionDetail>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clientGetPendingAction
     *
     * @param actionId 
     * @return RequestConfig
     */
    fun clientGetPendingActionRequestConfig(actionId: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/pending-actions/{action_id}".replace("{"+"action_id"+"}", encodeURIComponent(actionId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/runs/{run_id}
     * Get one client run
     * 
     * @param runId 
     * @return Run
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clientGetRun(runId: kotlin.String) : Run {
        val localVarResponse = clientGetRunWithHttpInfo(runId = runId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Run
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/runs/{run_id}
     * Get one client run
     * 
     * @param runId 
     * @return ApiResponse<Run?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clientGetRunWithHttpInfo(runId: kotlin.String) : ApiResponse<Run?> {
        val localVariableConfig = clientGetRunRequestConfig(runId = runId)

        return request<Unit, Run>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clientGetRun
     *
     * @param runId 
     * @return RequestConfig
     */
    fun clientGetRunRequestConfig(runId: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/runs/{run_id}".replace("{"+"run_id"+"}", encodeURIComponent(runId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/runs/{run_id}/detail
     * Load the aggregate detail for a run
     * 
     * @param runId 
     * @return RunDetail
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clientGetRunDetail(runId: kotlin.String) : RunDetail {
        val localVarResponse = clientGetRunDetailWithHttpInfo(runId = runId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as RunDetail
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/runs/{run_id}/detail
     * Load the aggregate detail for a run
     * 
     * @param runId 
     * @return ApiResponse<RunDetail?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clientGetRunDetailWithHttpInfo(runId: kotlin.String) : ApiResponse<RunDetail?> {
        val localVariableConfig = clientGetRunDetailRequestConfig(runId = runId)

        return request<Unit, RunDetail>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clientGetRunDetail
     *
     * @param runId 
     * @return RequestConfig
     */
    fun clientGetRunDetailRequestConfig(runId: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/runs/{run_id}/detail".replace("{"+"run_id"+"}", encodeURIComponent(runId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/runs/{run_id}/events
     * Replay and optionally follow mobile live RunEvent SSE
     * The response is &#x60;text/event-stream&#x60;. Each SSE message uses &#x60;id: &lt;RunEvent.event_id&gt;&#x60;, &#x60;event: &lt;RunEvent.type&gt;&#x60;, and &#x60;data:&#x60; containing the full RunEvent JSON object. The endpoint emits only the mobile live event subset. &#x60;after_seq&#x60; is an exclusive persisted cursor over the existing events table, so the server may advance the cursor across diagnostic events that are not emitted. Mobile clients persist &#x60;{run_id,last_seq}&#x60; locally, pass &#x60;last_seq&#x60; as &#x60;after_seq&#x60;, receive backlog events first, and then receive live follow events when &#x60;follow&#x3D;true&#x60;. 
     * @param runId 
     * @param afterSeq  (optional, default to 0)
     * @param follow  (optional, default to false)
     * @return RunEvent
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clientGetRunEvents(runId: kotlin.String, afterSeq: kotlin.Int? = 0, follow: kotlin.Boolean? = false) : RunEvent {
        val localVarResponse = clientGetRunEventsWithHttpInfo(runId = runId, afterSeq = afterSeq, follow = follow)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as RunEvent
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/runs/{run_id}/events
     * Replay and optionally follow mobile live RunEvent SSE
     * The response is &#x60;text/event-stream&#x60;. Each SSE message uses &#x60;id: &lt;RunEvent.event_id&gt;&#x60;, &#x60;event: &lt;RunEvent.type&gt;&#x60;, and &#x60;data:&#x60; containing the full RunEvent JSON object. The endpoint emits only the mobile live event subset. &#x60;after_seq&#x60; is an exclusive persisted cursor over the existing events table, so the server may advance the cursor across diagnostic events that are not emitted. Mobile clients persist &#x60;{run_id,last_seq}&#x60; locally, pass &#x60;last_seq&#x60; as &#x60;after_seq&#x60;, receive backlog events first, and then receive live follow events when &#x60;follow&#x3D;true&#x60;. 
     * @param runId 
     * @param afterSeq  (optional, default to 0)
     * @param follow  (optional, default to false)
     * @return ApiResponse<RunEvent?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clientGetRunEventsWithHttpInfo(runId: kotlin.String, afterSeq: kotlin.Int?, follow: kotlin.Boolean?) : ApiResponse<RunEvent?> {
        val localVariableConfig = clientGetRunEventsRequestConfig(runId = runId, afterSeq = afterSeq, follow = follow)

        return request<Unit, RunEvent>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clientGetRunEvents
     *
     * @param runId 
     * @param afterSeq  (optional, default to 0)
     * @param follow  (optional, default to false)
     * @return RequestConfig
     */
    fun clientGetRunEventsRequestConfig(runId: kotlin.String, afterSeq: kotlin.Int?, follow: kotlin.Boolean?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (afterSeq != null) {
                    put("after_seq", listOf(afterSeq.toString()))
                }
                if (follow != null) {
                    put("follow", listOf(follow.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/runs/{run_id}/events".replace("{"+"run_id"+"}", encodeURIComponent(runId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * enum for parameter probeMcp
     */
     enum class ProbeMcpClientGetSystemStatus(val value: kotlin.String) {
         @Json(name = "1") _1("1");

        /**
         * Override [toString()] to avoid using the enum variable name as the value, and instead use
         * the actual value defined in the API spec file.
         *
         * This solves a problem when the variable name and its value are different, and ensures that
         * the client sends the correct enum values to the server always.
         */
        override fun toString(): kotlin.String = "$value"
     }

    /**
     * GET /v1/system/status
     * Load remote client system status
     * 
     * @param probeMcp Set to &#x60;1&#x60; to perform an explicit live MCP provider probe. Omit for passive capability reads. (optional)
     * @return SystemStatus
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clientGetSystemStatus(probeMcp: ProbeMcpClientGetSystemStatus? = null) : SystemStatus {
        val localVarResponse = clientGetSystemStatusWithHttpInfo(probeMcp = probeMcp)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SystemStatus
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/system/status
     * Load remote client system status
     * 
     * @param probeMcp Set to &#x60;1&#x60; to perform an explicit live MCP provider probe. Omit for passive capability reads. (optional)
     * @return ApiResponse<SystemStatus?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clientGetSystemStatusWithHttpInfo(probeMcp: ProbeMcpClientGetSystemStatus?) : ApiResponse<SystemStatus?> {
        val localVariableConfig = clientGetSystemStatusRequestConfig(probeMcp = probeMcp)

        return request<Unit, SystemStatus>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clientGetSystemStatus
     *
     * @param probeMcp Set to &#x60;1&#x60; to perform an explicit live MCP provider probe. Omit for passive capability reads. (optional)
     * @return RequestConfig
     */
    fun clientGetSystemStatusRequestConfig(probeMcp: ProbeMcpClientGetSystemStatus?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (probeMcp != null) {
                    put("probe_mcp", listOf(probeMcp.value))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/system/status",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/threads/{thread_id}
     * Get one client thread
     * 
     * @param threadId 
     * @return Thread
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clientGetThread(threadId: kotlin.String) : Thread {
        val localVarResponse = clientGetThreadWithHttpInfo(threadId = threadId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Thread
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/threads/{thread_id}
     * Get one client thread
     * 
     * @param threadId 
     * @return ApiResponse<Thread?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clientGetThreadWithHttpInfo(threadId: kotlin.String) : ApiResponse<Thread?> {
        val localVariableConfig = clientGetThreadRequestConfig(threadId = threadId)

        return request<Unit, Thread>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clientGetThread
     *
     * @param threadId 
     * @return RequestConfig
     */
    fun clientGetThreadRequestConfig(threadId: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/threads/{thread_id}".replace("{"+"thread_id"+"}", encodeURIComponent(threadId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/runs/{run_id}:interrupt
     * Request interruption for a running client run
     * 
     * @param runId 
     * @return InterruptRunResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clientInterruptRun(runId: kotlin.String) : InterruptRunResponse {
        val localVarResponse = clientInterruptRunWithHttpInfo(runId = runId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as InterruptRunResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/runs/{run_id}:interrupt
     * Request interruption for a running client run
     * 
     * @param runId 
     * @return ApiResponse<InterruptRunResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clientInterruptRunWithHttpInfo(runId: kotlin.String) : ApiResponse<InterruptRunResponse?> {
        val localVariableConfig = clientInterruptRunRequestConfig(runId = runId)

        return request<Unit, InterruptRunResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clientInterruptRun
     *
     * @param runId 
     * @return RequestConfig
     */
    fun clientInterruptRunRequestConfig(runId: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/runs/{run_id}:interrupt".replace("{"+"run_id"+"}", encodeURIComponent(runId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/threads/{thread_id}/messages
     * List messages for a client thread
     * 
     * @param threadId 
     * @param limit Positive integer limit. Defaults to 100. (optional)
     * @return MessageListResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clientListMessages(threadId: kotlin.String, limit: kotlin.Int? = null) : MessageListResponse {
        val localVarResponse = clientListMessagesWithHttpInfo(threadId = threadId, limit = limit)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MessageListResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/threads/{thread_id}/messages
     * List messages for a client thread
     * 
     * @param threadId 
     * @param limit Positive integer limit. Defaults to 100. (optional)
     * @return ApiResponse<MessageListResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clientListMessagesWithHttpInfo(threadId: kotlin.String, limit: kotlin.Int?) : ApiResponse<MessageListResponse?> {
        val localVariableConfig = clientListMessagesRequestConfig(threadId = threadId, limit = limit)

        return request<Unit, MessageListResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clientListMessages
     *
     * @param threadId 
     * @param limit Positive integer limit. Defaults to 100. (optional)
     * @return RequestConfig
     */
    fun clientListMessagesRequestConfig(threadId: kotlin.String, limit: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/threads/{thread_id}/messages".replace("{"+"thread_id"+"}", encodeURIComponent(threadId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/pending-actions
     * List actionable pending client actions
     * 
     * @param limit Positive integer limit. Defaults to 100. (optional)
     * @return PendingActionListResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clientListPendingActions(limit: kotlin.Int? = null) : PendingActionListResponse {
        val localVarResponse = clientListPendingActionsWithHttpInfo(limit = limit)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as PendingActionListResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/pending-actions
     * List actionable pending client actions
     * 
     * @param limit Positive integer limit. Defaults to 100. (optional)
     * @return ApiResponse<PendingActionListResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clientListPendingActionsWithHttpInfo(limit: kotlin.Int?) : ApiResponse<PendingActionListResponse?> {
        val localVariableConfig = clientListPendingActionsRequestConfig(limit = limit)

        return request<Unit, PendingActionListResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clientListPendingActions
     *
     * @param limit Positive integer limit. Defaults to 100. (optional)
     * @return RequestConfig
     */
    fun clientListPendingActionsRequestConfig(limit: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/pending-actions",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/threads
     * List client threads
     * 
     * @param limit Positive integer limit. Defaults to 100. (optional)
     * @return ThreadListResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clientListThreads(limit: kotlin.Int? = null) : ThreadListResponse {
        val localVarResponse = clientListThreadsWithHttpInfo(limit = limit)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ThreadListResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/threads
     * List client threads
     * 
     * @param limit Positive integer limit. Defaults to 100. (optional)
     * @return ApiResponse<ThreadListResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clientListThreadsWithHttpInfo(limit: kotlin.Int?) : ApiResponse<ThreadListResponse?> {
        val localVariableConfig = clientListThreadsRequestConfig(limit = limit)

        return request<Unit, ThreadListResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clientListThreads
     *
     * @param limit Positive integer limit. Defaults to 100. (optional)
     * @return RequestConfig
     */
    fun clientListThreadsRequestConfig(limit: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/threads",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * enum for parameter probeMcp
     */
     enum class ProbeMcpClientListTools(val value: kotlin.String) {
         @Json(name = "1") _1("1");

        /**
         * Override [toString()] to avoid using the enum variable name as the value, and instead use
         * the actual value defined in the API spec file.
         *
         * This solves a problem when the variable name and its value are different, and ensures that
         * the client sends the correct enum values to the server always.
         */
        override fun toString(): kotlin.String = "$value"
     }

    /**
     * GET /v1/tools
     * List tools for remote clients
     * 
     * @param probeMcp Set to &#x60;1&#x60; to perform an explicit live MCP provider probe. Omit for passive capability reads. (optional)
     * @return ToolListResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clientListTools(probeMcp: ProbeMcpClientListTools? = null) : ToolListResponse {
        val localVarResponse = clientListToolsWithHttpInfo(probeMcp = probeMcp)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ToolListResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/tools
     * List tools for remote clients
     * 
     * @param probeMcp Set to &#x60;1&#x60; to perform an explicit live MCP provider probe. Omit for passive capability reads. (optional)
     * @return ApiResponse<ToolListResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clientListToolsWithHttpInfo(probeMcp: ProbeMcpClientListTools?) : ApiResponse<ToolListResponse?> {
        val localVariableConfig = clientListToolsRequestConfig(probeMcp = probeMcp)

        return request<Unit, ToolListResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clientListTools
     *
     * @param probeMcp Set to &#x60;1&#x60; to perform an explicit live MCP provider probe. Omit for passive capability reads. (optional)
     * @return RequestConfig
     */
    fun clientListToolsRequestConfig(probeMcp: ProbeMcpClientListTools?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (probeMcp != null) {
                    put("probe_mcp", listOf(probeMcp.value))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/tools",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/runs/{run_id}:resume
     * Resume an interrupted client run
     * 
     * @param runId 
     * @return RunResult
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clientResumeRun(runId: kotlin.String) : RunResult {
        val localVarResponse = clientResumeRunWithHttpInfo(runId = runId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as RunResult
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/runs/{run_id}:resume
     * Resume an interrupted client run
     * 
     * @param runId 
     * @return ApiResponse<RunResult?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clientResumeRunWithHttpInfo(runId: kotlin.String) : ApiResponse<RunResult?> {
        val localVariableConfig = clientResumeRunRequestConfig(runId = runId)

        return request<Unit, RunResult>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clientResumeRun
     *
     * @param runId 
     * @return RequestConfig
     */
    fun clientResumeRunRequestConfig(runId: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/runs/{run_id}:resume".replace("{"+"run_id"+"}", encodeURIComponent(runId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PATCH /v1/threads/{thread_id}
     * Update a client thread
     * 
     * @param threadId 
     * @param updateThreadRequest 
     * @return Thread
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clientUpdateThread(threadId: kotlin.String, updateThreadRequest: UpdateThreadRequest) : Thread {
        val localVarResponse = clientUpdateThreadWithHttpInfo(threadId = threadId, updateThreadRequest = updateThreadRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Thread
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /v1/threads/{thread_id}
     * Update a client thread
     * 
     * @param threadId 
     * @param updateThreadRequest 
     * @return ApiResponse<Thread?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clientUpdateThreadWithHttpInfo(threadId: kotlin.String, updateThreadRequest: UpdateThreadRequest) : ApiResponse<Thread?> {
        val localVariableConfig = clientUpdateThreadRequestConfig(threadId = threadId, updateThreadRequest = updateThreadRequest)

        return request<UpdateThreadRequest, Thread>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clientUpdateThread
     *
     * @param threadId 
     * @param updateThreadRequest 
     * @return RequestConfig
     */
    fun clientUpdateThreadRequestConfig(threadId: kotlin.String, updateThreadRequest: UpdateThreadRequest) : RequestConfig<UpdateThreadRequest> {
        val localVariableBody = updateThreadRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/v1/threads/{thread_id}".replace("{"+"thread_id"+"}", encodeURIComponent(threadId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
