/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import io.ycvk.acorn.api.models.ErrorResponse
import io.ycvk.acorn.api.models.PhoneNotificationAccepted
import io.ycvk.acorn.api.models.PhoneNotificationBatch

import com.squareup.moshi.Json

import io.ycvk.acorn.api.infrastructure.ApiClient
import io.ycvk.acorn.api.infrastructure.ApiResponse
import io.ycvk.acorn.api.infrastructure.ClientException
import io.ycvk.acorn.api.infrastructure.ClientError
import io.ycvk.acorn.api.infrastructure.ServerException
import io.ycvk.acorn.api.infrastructure.ServerError
import io.ycvk.acorn.api.infrastructure.MultiValueMap
import io.ycvk.acorn.api.infrastructure.PartConfig
import io.ycvk.acorn.api.infrastructure.RequestConfig
import io.ycvk.acorn.api.infrastructure.RequestMethod
import io.ycvk.acorn.api.infrastructure.ResponseType
import io.ycvk.acorn.api.infrastructure.Success
import io.ycvk.acorn.api.infrastructure.toMultiValue

open class PhoneNotificationsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "http://127.0.0.1:8080")
        }
    }

    /**
     * POST /v1/phone-notifications
     * Upload notifications captured by this device
     * Stores background signals without waking the agent. Entries are deduplicated by authenticated device, key and posted_at. Raw signals are retained for seven days; derived conversation, context snapshot and knowledge records follow their own retention.
     * @param phoneNotificationBatch 
     * @return PhoneNotificationAccepted
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clientPostPhoneNotifications(phoneNotificationBatch: PhoneNotificationBatch) : PhoneNotificationAccepted {
        val localVarResponse = clientPostPhoneNotificationsWithHttpInfo(phoneNotificationBatch = phoneNotificationBatch)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as PhoneNotificationAccepted
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/phone-notifications
     * Upload notifications captured by this device
     * Stores background signals without waking the agent. Entries are deduplicated by authenticated device, key and posted_at. Raw signals are retained for seven days; derived conversation, context snapshot and knowledge records follow their own retention.
     * @param phoneNotificationBatch 
     * @return ApiResponse<PhoneNotificationAccepted?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clientPostPhoneNotificationsWithHttpInfo(phoneNotificationBatch: PhoneNotificationBatch) : ApiResponse<PhoneNotificationAccepted?> {
        val localVariableConfig = clientPostPhoneNotificationsRequestConfig(phoneNotificationBatch = phoneNotificationBatch)

        return request<PhoneNotificationBatch, PhoneNotificationAccepted>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clientPostPhoneNotifications
     *
     * @param phoneNotificationBatch 
     * @return RequestConfig
     */
    fun clientPostPhoneNotificationsRequestConfig(phoneNotificationBatch: PhoneNotificationBatch) : RequestConfig<PhoneNotificationBatch> {
        val localVariableBody = phoneNotificationBatch
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/phone-notifications",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
