/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import io.ycvk.acorn.api.models.ClientWebhookTrigger202Response
import io.ycvk.acorn.api.models.Error

import com.squareup.moshi.Json

import io.ycvk.acorn.api.infrastructure.ApiClient
import io.ycvk.acorn.api.infrastructure.ApiResponse
import io.ycvk.acorn.api.infrastructure.ClientException
import io.ycvk.acorn.api.infrastructure.ClientError
import io.ycvk.acorn.api.infrastructure.ServerException
import io.ycvk.acorn.api.infrastructure.ServerError
import io.ycvk.acorn.api.infrastructure.MultiValueMap
import io.ycvk.acorn.api.infrastructure.PartConfig
import io.ycvk.acorn.api.infrastructure.RequestConfig
import io.ycvk.acorn.api.infrastructure.RequestMethod
import io.ycvk.acorn.api.infrastructure.ResponseType
import io.ycvk.acorn.api.infrastructure.Success
import io.ycvk.acorn.api.infrastructure.toMultiValue

open class TriggersApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "http://127.0.0.1:8080")
        }
    }

    /**
     * POST /v1/triggers/{trigger_id}
     * Receive an external webhook and fire a trigger
     * Endpoint for ambient webhook triggers. Not behind device auth — authentication is via HMAC-SHA256 signature (X-Acorn-Signature header). When a trigger fires, the scheduler starts a new run on a trigger-specific thread. 
     * @param triggerId The trigger ID configured in triggers.webhooks
     * @param body 
     * @return ClientWebhookTrigger202Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clientWebhookTrigger(triggerId: kotlin.String, body: kotlin.String) : ClientWebhookTrigger202Response {
        val localVarResponse = clientWebhookTriggerWithHttpInfo(triggerId = triggerId, body = body)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ClientWebhookTrigger202Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/triggers/{trigger_id}
     * Receive an external webhook and fire a trigger
     * Endpoint for ambient webhook triggers. Not behind device auth — authentication is via HMAC-SHA256 signature (X-Acorn-Signature header). When a trigger fires, the scheduler starts a new run on a trigger-specific thread. 
     * @param triggerId The trigger ID configured in triggers.webhooks
     * @param body 
     * @return ApiResponse<ClientWebhookTrigger202Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clientWebhookTriggerWithHttpInfo(triggerId: kotlin.String, body: kotlin.String) : ApiResponse<ClientWebhookTrigger202Response?> {
        val localVariableConfig = clientWebhookTriggerRequestConfig(triggerId = triggerId, body = body)

        return request<kotlin.String, ClientWebhookTrigger202Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clientWebhookTrigger
     *
     * @param triggerId The trigger ID configured in triggers.webhooks
     * @param body 
     * @return RequestConfig
     */
    fun clientWebhookTriggerRequestConfig(triggerId: kotlin.String, body: kotlin.String) : RequestConfig<kotlin.String> {
        val localVariableBody = body
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/triggers/{trigger_id}".replace("{"+"trigger_id"+"}", encodeURIComponent(triggerId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
