package stream

type StreamItemKind string

const (
	StreamKindRunStarted                      StreamItemKind = "run_started"
	StreamKindRunCompleted                    StreamItemKind = "run_completed"
	StreamKindRunFailed                       StreamItemKind = "run_failed"
	StreamKindRunInterrupted                  StreamItemKind = "run_interrupted"
	StreamKindRunResumeRequested              StreamItemKind = "run_resume_requested"
	StreamKindDecisionSelected                StreamItemKind = "decision_selected"
	StreamKindDecisionBlocked                 StreamItemKind = "decision_blocked"
	StreamKindSkillDiscovered                 StreamItemKind = "skill_discovered"
	StreamKindSkillSelected                   StreamItemKind = "skill_selected"
	StreamKindSkillLoaded                     StreamItemKind = "skill_loaded"
	StreamKindSkillFailed                     StreamItemKind = "skill_failed"
	StreamKindSkillLifecycle                  StreamItemKind = "skill.lifecycle"
	StreamKindProcedureActivation             StreamItemKind = "procedure.activation"
	StreamKindMemoryPrepared                  StreamItemKind = "memory_prepared"
	StreamKindContextPressure                 StreamItemKind = "context_pressure"
	StreamKindContextCompressed               StreamItemKind = "context_compressed"
	StreamKindAssistantDelta                  StreamItemKind = "assistant.delta"
	StreamKindAssistantMessage                StreamItemKind = "assistant_message"
	StreamKindToolCallStarted                 StreamItemKind = "tool_call_started"
	StreamKindToolCallSucceeded               StreamItemKind = "tool_call_succeeded"
	StreamKindToolCallFailed                  StreamItemKind = "tool_call_failed"
	StreamKindToolCallInterrupted             StreamItemKind = "tool_call_interrupted"
	StreamKindProviderDegraded                StreamItemKind = "provider.degraded"
	StreamKindMCPToolCatalogRefreshed         StreamItemKind = "mcp.tool_catalog_refreshed"
	StreamKindMCPToolCatalogRefreshFailed     StreamItemKind = "mcp.tool_catalog_refresh_failed"
	StreamKindMCPProviderAdded                StreamItemKind = "mcp.provider_added"
	StreamKindMCPProviderRemoved              StreamItemKind = "mcp.provider_removed"
	StreamKindMCPProviderRestarted            StreamItemKind = "mcp.provider_restarted"
	StreamKindMCPResourceCatalogRefreshed     StreamItemKind = "mcp.resource_catalog_refreshed"
	StreamKindMCPResourceCatalogRefreshFailed StreamItemKind = "mcp.resource_catalog_refresh_failed"
	StreamKindMCPPromptCatalogRefreshed       StreamItemKind = "mcp.prompt_catalog_refreshed"
	StreamKindMCPPromptCatalogRefreshFailed   StreamItemKind = "mcp.prompt_catalog_refresh_failed"
	StreamKindMCPAuthStatusChanged            StreamItemKind = "mcp.auth_status_changed"
	StreamKindElicitationPending              StreamItemKind = "elicitation.pending"
	StreamKindElicitationDecided              StreamItemKind = "elicitation.decided"
	StreamKindSamplingStarted                 StreamItemKind = "sampling.started"
	StreamKindSamplingCompleted               StreamItemKind = "sampling.completed"
	StreamKindSamplingFailed                  StreamItemKind = "sampling.failed"
	StreamKindSubagentStarted                 StreamItemKind = "subagent.started"
	StreamKindSubagentCompleted               StreamItemKind = "subagent.completed"
	StreamKindSubagentFailed                  StreamItemKind = "subagent.failed"
	StreamKindPlanCreated                     StreamItemKind = "plan.created"
	StreamKindPlanUpdated                     StreamItemKind = "plan.updated"
	StreamKindPlanCleared                     StreamItemKind = "plan.cleared"
	StreamKindStepStarted                     StreamItemKind = "step.started"
	StreamKindStepCompleted                   StreamItemKind = "step.completed"
	StreamKindStepFailed                      StreamItemKind = "step.failed"
)
