// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package web

import (
	app "github.com/ycvk/acorn/internal/app"
	memorymodule "github.com/ycvk/acorn/internal/memorymodule"
	skills "github.com/ycvk/acorn/internal/skills"
)

type ConverterImpl struct{}

func (c *ConverterImpl) appArtifactSummaryToWebArtifactSummaryDTO(source app.ArtifactSummary) ArtifactSummaryDTO {
	var webArtifactSummaryDTO ArtifactSummaryDTO
	webArtifactSummaryDTO.ArtifactID = source.ArtifactID
	webArtifactSummaryDTO.RunID = source.RunID
	webArtifactSummaryDTO.SessionID = source.SessionID
	webArtifactSummaryDTO.SourceToolResultRef = source.SourceToolResultRef
	webArtifactSummaryDTO.Kind = source.Kind
	webArtifactSummaryDTO.Title = source.Title
	webArtifactSummaryDTO.MIMEType = source.MIMEType
	webArtifactSummaryDTO.SizeBytes = source.SizeBytes
	webArtifactSummaryDTO.SHA256 = source.SHA256
	webArtifactSummaryDTO.CreatedAt = TimeToTime(source.CreatedAt)
	return webArtifactSummaryDTO
}
func (c *ConverterImpl) appDecisionOptionToWebDecisionOptionDTO(source app.DecisionOption) DecisionOptionDTO {
	var webDecisionOptionDTO DecisionOptionDTO
	webDecisionOptionDTO.ID = source.ID
	webDecisionOptionDTO.Label = source.Label
	webDecisionOptionDTO.Description = source.Description
	return webDecisionOptionDTO
}
func (c *ConverterImpl) appDisclosureItemToWebDisclosureItemDTO(source app.DisclosureItem) DisclosureItemDTO {
	var webDisclosureItemDTO DisclosureItemDTO
	webDisclosureItemDTO.Kind = source.Kind
	webDisclosureItemDTO.Label = source.Label
	webDisclosureItemDTO.Detail = source.Detail
	webDisclosureItemDTO.Tone = source.Tone
	webDisclosureItemDTO.SkillID = source.SkillID
	return webDisclosureItemDTO
}
func (c *ConverterImpl) appMessageContentToWebMessageContentDTO(source app.MessageContent) MessageContentDTO {
	var webMessageContentDTO MessageContentDTO
	webMessageContentDTO.Type = source.Type
	webMessageContentDTO.Text = source.Text
	if source.Parts != nil {
		webMessageContentDTO.Parts = make([]MessagePartDTO, len(source.Parts))
		for i := 0; i < len(source.Parts); i++ {
			webMessageContentDTO.Parts[i] = c.appMessagePartToWebMessagePartDTO(source.Parts[i])
		}
	}
	return webMessageContentDTO
}
func (c *ConverterImpl) appMessagePartToWebMessagePartDTO(source app.MessagePart) MessagePartDTO {
	var webMessagePartDTO MessagePartDTO
	webMessagePartDTO.Kind = source.Kind
	webMessagePartDTO.Text = source.Text
	webMessagePartDTO.Reasoning = source.Reasoning
	webMessagePartDTO.Status = source.Status
	webMessagePartDTO.Title = source.Title
	webMessagePartDTO.Summary = source.Summary
	if source.Changed != nil {
		webMessagePartDTO.Changed = make([]string, len(source.Changed))
		for i := 0; i < len(source.Changed); i++ {
			webMessagePartDTO.Changed[i] = source.Changed[i]
		}
	}
	if source.Verified != nil {
		webMessagePartDTO.Verified = make([]string, len(source.Verified))
		for j := 0; j < len(source.Verified); j++ {
			webMessagePartDTO.Verified[j] = source.Verified[j]
		}
	}
	if source.Risks != nil {
		webMessagePartDTO.Risks = make([]string, len(source.Risks))
		for k := 0; k < len(source.Risks); k++ {
			webMessagePartDTO.Risks[k] = source.Risks[k]
		}
	}
	webMessagePartDTO.Items = c.disclosureItemDTOsFromDomain(source.Items)
	webMessagePartDTO.DetailRunID = source.DetailRunID
	webMessagePartDTO.RunID = source.RunID
	webMessagePartDTO.Label = source.Label
	webMessagePartDTO.DecisionID = source.DecisionID
	webMessagePartDTO.Question = source.Question
	webMessagePartDTO.SelectedOptionID = source.SelectedOptionID
	webMessagePartDTO.Answer = source.Answer
	webMessagePartDTO.Options = c.decisionOptionDTOsFromDomain(source.Options)
	webMessagePartDTO.Action = c.pAppMessageActionToPWebMessageActionDTO(source.Action)
	return webMessagePartDTO
}
func (c *ConverterImpl) appPendingActionOptionToWebPendingActionOptionDTO(source app.PendingActionOption) PendingActionOptionDTO {
	var webPendingActionOptionDTO PendingActionOptionDTO
	webPendingActionOptionDTO.ID = source.ID
	webPendingActionOptionDTO.Label = source.Label
	webPendingActionOptionDTO.Description = source.Description
	return webPendingActionOptionDTO
}
func (c *ConverterImpl) appPendingActionSummaryToWebPendingActionSummaryDTO(source app.PendingActionSummary) PendingActionSummaryDTO {
	var webPendingActionSummaryDTO PendingActionSummaryDTO
	webPendingActionSummaryDTO.ActionID = source.ActionID
	webPendingActionSummaryDTO.RunID = source.RunID
	webPendingActionSummaryDTO.ThreadID = source.ThreadID
	webPendingActionSummaryDTO.Kind = source.Kind
	webPendingActionSummaryDTO.Status = source.Status
	webPendingActionSummaryDTO.Title = source.Title
	webPendingActionSummaryDTO.Body = source.Body
	webPendingActionSummaryDTO.Options = c.pendingActionOptionDTOsFromDomain(source.Options)
	webPendingActionSummaryDTO.CreatedAt = TimeToTime(source.CreatedAt)
	return webPendingActionSummaryDTO
}
func (c *ConverterImpl) appProviderReadinessSummaryToWebProviderReadinessDTO(source app.ProviderReadinessSummary) ProviderReadinessDTO {
	var webProviderReadinessDTO ProviderReadinessDTO
	webProviderReadinessDTO.Scope = source.Scope
	webProviderReadinessDTO.Provider = source.Provider
	webProviderReadinessDTO.Status = string(source.Status)
	webProviderReadinessDTO.Reason = source.Reason
	webProviderReadinessDTO.StartupStatus = source.StartupStatus
	webProviderReadinessDTO.AuthStatus = source.AuthStatus
	return webProviderReadinessDTO
}
func (c *ConverterImpl) appRunSummaryToWebRunSummaryDTO(source app.RunSummary) RunSummaryDTO {
	var webRunSummaryDTO RunSummaryDTO
	webRunSummaryDTO.RunID = source.RunID
	webRunSummaryDTO.ThreadID = source.ThreadID
	webRunSummaryDTO.ThreadTitle = source.ThreadTitle
	webRunSummaryDTO.Status = source.Status
	webRunSummaryDTO.Mode = source.Mode
	webRunSummaryDTO.Preview = source.Preview
	webRunSummaryDTO.LastEventLabel = source.LastEventLabel
	webRunSummaryDTO.AttentionLevel = source.AttentionLevel
	webRunSummaryDTO.DurationMS = source.DurationMS
	webRunSummaryDTO.CreatedAt = TimeToTime(source.CreatedAt)
	webRunSummaryDTO.UpdatedAt = TimeToTime(source.UpdatedAt)
	return webRunSummaryDTO
}
func (c *ConverterImpl) appSystemToolCapabilityToWebCapabilitiesToolDTO(source app.SystemToolCapability) CapabilitiesToolDTO {
	var webCapabilitiesToolDTO CapabilitiesToolDTO
	webCapabilitiesToolDTO.Name = source.Name
	webCapabilitiesToolDTO.Source = source.Source
	webCapabilitiesToolDTO.Kind = source.Kind
	webCapabilitiesToolDTO.Category = source.Category
	webCapabilitiesToolDTO.Enabled = source.Enabled
	webCapabilitiesToolDTO.HealthState = source.HealthState
	webCapabilitiesToolDTO.HealthReason = source.HealthReason
	webCapabilitiesToolDTO.ParallelPolicy = source.ParallelPolicy
	webCapabilitiesToolDTO.Risk = source.Risk
	webCapabilitiesToolDTO.RootDir = source.RootDir
	webCapabilitiesToolDTO.WorkDir = source.WorkDir
	webCapabilitiesToolDTO.DefaultTimeout = source.DefaultTimeout
	return webCapabilitiesToolDTO
}
func (c *ConverterImpl) artifactSummaryDTOsFromDomain(source []app.ArtifactSummary) []ArtifactSummaryDTO {
	var webArtifactSummaryDTOList []ArtifactSummaryDTO
	if source != nil {
		webArtifactSummaryDTOList = make([]ArtifactSummaryDTO, len(source))
		for i := 0; i < len(source); i++ {
			webArtifactSummaryDTOList[i] = c.appArtifactSummaryToWebArtifactSummaryDTO(source[i])
		}
	}
	return webArtifactSummaryDTOList
}
func (c *ConverterImpl) capabilitiesFeaturesDTOFromSnapshot(source app.SystemFeatureCapabilities) CapabilitiesFeaturesDTO {
	var webCapabilitiesFeaturesDTO CapabilitiesFeaturesDTO
	webCapabilitiesFeaturesDTO.InterruptResume = source.InterruptResume
	webCapabilitiesFeaturesDTO.SessionHistory = source.SessionHistory
	return webCapabilitiesFeaturesDTO
}
func (c *ConverterImpl) capabilitiesModelDTOFromSnapshot(source app.SystemModelCapabilities) CapabilitiesModelDTO {
	var webCapabilitiesModelDTO CapabilitiesModelDTO
	webCapabilitiesModelDTO.Name = source.Name
	return webCapabilitiesModelDTO
}
func (c *ConverterImpl) capabilitiesSummaryDTOFromSnapshot(source app.SystemCapabilitySummary) CapabilitiesSummaryDTO {
	var webCapabilitiesSummaryDTO CapabilitiesSummaryDTO
	webCapabilitiesSummaryDTO.ToolCount = source.ToolCount
	webCapabilitiesSummaryDTO.EnabledToolCount = source.EnabledToolCount
	webCapabilitiesSummaryDTO.SkillCount = source.SkillCount
	webCapabilitiesSummaryDTO.EligibleSkillCount = source.EligibleSkillCount
	webCapabilitiesSummaryDTO.IneligibleSkillCount = source.IneligibleSkillCount
	webCapabilitiesSummaryDTO.InvalidSkillCount = source.InvalidSkillCount
	webCapabilitiesSummaryDTO.MCPConfiguredProviderCount = source.MCPConfiguredProviderCount
	webCapabilitiesSummaryDTO.MCPEnabledProviderCount = source.MCPEnabledProviderCount
	webCapabilitiesSummaryDTO.MCPHealthyProviderCount = source.MCPHealthyProviderCount
	return webCapabilitiesSummaryDTO
}
func (c *ConverterImpl) capabilitiesToolsDTOFromSnapshot(source []app.SystemToolCapability) []CapabilitiesToolDTO {
	var webCapabilitiesToolDTOList []CapabilitiesToolDTO
	if source != nil {
		webCapabilitiesToolDTOList = make([]CapabilitiesToolDTO, len(source))
		for i := 0; i < len(source); i++ {
			webCapabilitiesToolDTOList[i] = c.appSystemToolCapabilityToWebCapabilitiesToolDTO(source[i])
		}
	}
	return webCapabilitiesToolDTOList
}
func (c *ConverterImpl) decisionOptionDTOsFromDomain(source []app.DecisionOption) []DecisionOptionDTO {
	var webDecisionOptionDTOList []DecisionOptionDTO
	if source != nil {
		webDecisionOptionDTOList = make([]DecisionOptionDTO, len(source))
		for i := 0; i < len(source); i++ {
			webDecisionOptionDTOList[i] = c.appDecisionOptionToWebDecisionOptionDTO(source[i])
		}
	}
	return webDecisionOptionDTOList
}
func (c *ConverterImpl) disclosureItemDTOsFromDomain(source []app.DisclosureItem) []DisclosureItemDTO {
	var webDisclosureItemDTOList []DisclosureItemDTO
	if source != nil {
		webDisclosureItemDTOList = make([]DisclosureItemDTO, len(source))
		for i := 0; i < len(source); i++ {
			webDisclosureItemDTOList[i] = c.appDisclosureItemToWebDisclosureItemDTO(source[i])
		}
	}
	return webDisclosureItemDTOList
}
func (c *ConverterImpl) memoryRecordDTOFromDomain(source memorymodule.Record) MemoryRecordDTO {
	var webMemoryRecordDTO MemoryRecordDTO
	webMemoryRecordDTO.Ref = source.Ref
	webMemoryRecordDTO.Kind = string(source.Kind)
	webMemoryRecordDTO.Title = source.Title
	webMemoryRecordDTO.Status = string(source.Status)
	webMemoryRecordDTO.Scope = source.Scope
	if source.Tags != nil {
		webMemoryRecordDTO.Tags = make([]string, len(source.Tags))
		for i := 0; i < len(source.Tags); i++ {
			webMemoryRecordDTO.Tags[i] = source.Tags[i]
		}
	}
	webMemoryRecordDTO.Origin = source.Origin
	webMemoryRecordDTO.TaskPattern = source.TaskPattern
	webMemoryRecordDTO.Path = source.RelPath
	webMemoryRecordDTO.Body = source.Body
	webMemoryRecordDTO.Created = source.Created
	webMemoryRecordDTO.Updated = source.Updated
	webMemoryRecordDTO.ValidFrom = source.ValidFrom
	webMemoryRecordDTO.ValidUntil = source.ValidUntil
	webMemoryRecordDTO.SourceRun = source.SourceRun
	if source.SourceRefs != nil {
		webMemoryRecordDTO.SourceRefs = make([]string, len(source.SourceRefs))
		for j := 0; j < len(source.SourceRefs); j++ {
			webMemoryRecordDTO.SourceRefs[j] = source.SourceRefs[j]
		}
	}
	if source.EvidenceRefs != nil {
		webMemoryRecordDTO.EvidenceRefs = make([]string, len(source.EvidenceRefs))
		for k := 0; k < len(source.EvidenceRefs); k++ {
			webMemoryRecordDTO.EvidenceRefs[k] = source.EvidenceRefs[k]
		}
	}
	webMemoryRecordDTO.Relations = c.memoryRecordRelationDTOsFromDomain(source.Relations)
	return webMemoryRecordDTO
}
func (c *ConverterImpl) memoryRecordDTOsFromDomain(source []memorymodule.Record) []MemoryRecordDTO {
	var webMemoryRecordDTOList []MemoryRecordDTO
	if source != nil {
		webMemoryRecordDTOList = make([]MemoryRecordDTO, len(source))
		for i := 0; i < len(source); i++ {
			webMemoryRecordDTOList[i] = c.memoryRecordDTOFromDomain(source[i])
		}
	}
	return webMemoryRecordDTOList
}
func (c *ConverterImpl) memoryRecordRelationDTOsFromDomain(source []memorymodule.RecordRelation) []MemoryRecordRelationDTO {
	var webMemoryRecordRelationDTOList []MemoryRecordRelationDTO
	if source != nil {
		webMemoryRecordRelationDTOList = make([]MemoryRecordRelationDTO, len(source))
		for i := 0; i < len(source); i++ {
			webMemoryRecordRelationDTOList[i] = c.memorymoduleRecordRelationToWebMemoryRecordRelationDTO(source[i])
		}
	}
	return webMemoryRecordRelationDTOList
}
func (c *ConverterImpl) memorySearchItemDTOsFromDomain(source []memorymodule.SearchItem) []MemorySearchItemDTO {
	var webMemorySearchItemDTOList []MemorySearchItemDTO
	if source != nil {
		webMemorySearchItemDTOList = make([]MemorySearchItemDTO, len(source))
		for i := 0; i < len(source); i++ {
			webMemorySearchItemDTOList[i] = c.memorymoduleSearchItemToWebMemorySearchItemDTO(source[i])
		}
	}
	return webMemorySearchItemDTOList
}
func (c *ConverterImpl) memorymoduleRecordRelationToWebMemoryRecordRelationDTO(source memorymodule.RecordRelation) MemoryRecordRelationDTO {
	var webMemoryRecordRelationDTO MemoryRecordRelationDTO
	webMemoryRecordRelationDTO.Type = string(source.Type)
	webMemoryRecordRelationDTO.Target = source.Target
	webMemoryRecordRelationDTO.Reason = source.Reason
	return webMemoryRecordRelationDTO
}
func (c *ConverterImpl) memorymoduleSearchItemToWebMemorySearchItemDTO(source memorymodule.SearchItem) MemorySearchItemDTO {
	var webMemorySearchItemDTO MemorySearchItemDTO
	webMemorySearchItemDTO.Ref = source.Ref
	webMemorySearchItemDTO.Kind = source.Kind
	webMemorySearchItemDTO.Title = source.Title
	webMemorySearchItemDTO.Status = source.Status
	webMemorySearchItemDTO.Scope = source.Scope
	if source.Tags != nil {
		webMemorySearchItemDTO.Tags = make([]string, len(source.Tags))
		for i := 0; i < len(source.Tags); i++ {
			webMemorySearchItemDTO.Tags[i] = source.Tags[i]
		}
	}
	webMemorySearchItemDTO.Origin = source.Origin
	webMemorySearchItemDTO.TaskPattern = source.TaskPattern
	webMemorySearchItemDTO.Path = source.Path
	webMemorySearchItemDTO.Snippet = source.Snippet
	webMemorySearchItemDTO.Score = source.Score
	webMemorySearchItemDTO.Created = source.Created
	webMemorySearchItemDTO.Updated = source.Updated
	webMemorySearchItemDTO.ValidFrom = source.ValidFrom
	webMemorySearchItemDTO.ValidUntil = source.ValidUntil
	webMemorySearchItemDTO.SourceRun = source.SourceRun
	if source.SourceRefs != nil {
		webMemorySearchItemDTO.SourceRefs = make([]string, len(source.SourceRefs))
		for j := 0; j < len(source.SourceRefs); j++ {
			webMemorySearchItemDTO.SourceRefs[j] = source.SourceRefs[j]
		}
	}
	if source.EvidenceRefs != nil {
		webMemorySearchItemDTO.EvidenceRefs = make([]string, len(source.EvidenceRefs))
		for k := 0; k < len(source.EvidenceRefs); k++ {
			webMemorySearchItemDTO.EvidenceRefs[k] = source.EvidenceRefs[k]
		}
	}
	webMemorySearchItemDTO.Relations = c.memoryRecordRelationDTOsFromDomain(source.Relations)
	return webMemorySearchItemDTO
}
func (c *ConverterImpl) messageDTOFromDomain(source app.Message) MessageDTO {
	var webMessageDTO MessageDTO
	webMessageDTO.ID = source.ID
	webMessageDTO.ThreadID = source.ThreadID
	webMessageDTO.Role = source.Role
	webMessageDTO.Content = c.appMessageContentToWebMessageContentDTO(source.Content)
	webMessageDTO.CreatedAt = TimeToTime(source.CreatedAt)
	webMessageDTO.RunID = source.RunID
	return webMessageDTO
}
func (c *ConverterImpl) messageDTOsFromDomain(source []app.Message) []MessageDTO {
	var webMessageDTOList []MessageDTO
	if source != nil {
		webMessageDTOList = make([]MessageDTO, len(source))
		for i := 0; i < len(source); i++ {
			webMessageDTOList[i] = c.messageDTOFromDomain(source[i])
		}
	}
	return webMessageDTOList
}
func (c *ConverterImpl) pAppMessageActionToPWebMessageActionDTO(source *app.MessageAction) *MessageActionDTO {
	var pWebMessageActionDTO *MessageActionDTO
	if source != nil {
		var webMessageActionDTO MessageActionDTO
		webMessageActionDTO.Kind = (*source).Kind
		webMessageActionDTO.RunID = (*source).RunID
		webMessageActionDTO.Label = (*source).Label
		pWebMessageActionDTO = &webMessageActionDTO
	}
	return pWebMessageActionDTO
}
func (c *ConverterImpl) pendingActionOptionDTOsFromDomain(source []app.PendingActionOption) []PendingActionOptionDTO {
	var webPendingActionOptionDTOList []PendingActionOptionDTO
	if source != nil {
		webPendingActionOptionDTOList = make([]PendingActionOptionDTO, len(source))
		for i := 0; i < len(source); i++ {
			webPendingActionOptionDTOList[i] = c.appPendingActionOptionToWebPendingActionOptionDTO(source[i])
		}
	}
	return webPendingActionOptionDTOList
}
func (c *ConverterImpl) pendingActionSummaryDTOsFromDomain(source []app.PendingActionSummary) []PendingActionSummaryDTO {
	var webPendingActionSummaryDTOList []PendingActionSummaryDTO
	if source != nil {
		webPendingActionSummaryDTOList = make([]PendingActionSummaryDTO, len(source))
		for i := 0; i < len(source); i++ {
			webPendingActionSummaryDTOList[i] = c.appPendingActionSummaryToWebPendingActionSummaryDTO(source[i])
		}
	}
	return webPendingActionSummaryDTOList
}
func (c *ConverterImpl) providerReadinessDTOsFromSnapshot(source []app.ProviderReadinessSummary) []ProviderReadinessDTO {
	var webProviderReadinessDTOList []ProviderReadinessDTO
	if source != nil {
		webProviderReadinessDTOList = make([]ProviderReadinessDTO, len(source))
		for i := 0; i < len(source); i++ {
			webProviderReadinessDTOList[i] = c.appProviderReadinessSummaryToWebProviderReadinessDTO(source[i])
		}
	}
	return webProviderReadinessDTOList
}
func (c *ConverterImpl) runSummaryDTOsFromDomain(source []app.RunSummary) []RunSummaryDTO {
	var webRunSummaryDTOList []RunSummaryDTO
	if source != nil {
		webRunSummaryDTOList = make([]RunSummaryDTO, len(source))
		for i := 0; i < len(source); i++ {
			webRunSummaryDTOList[i] = c.appRunSummaryToWebRunSummaryDTO(source[i])
		}
	}
	return webRunSummaryDTOList
}
func (c *ConverterImpl) skillRequirementsDTOFromDomain(source skills.Requirements) SkillRequirementsDTO {
	var webSkillRequirementsDTO SkillRequirementsDTO
	if source.Tools != nil {
		webSkillRequirementsDTO.Tools = make([]string, len(source.Tools))
		for i := 0; i < len(source.Tools); i++ {
			webSkillRequirementsDTO.Tools[i] = source.Tools[i]
		}
	}
	if source.Toolsets != nil {
		webSkillRequirementsDTO.Toolsets = make([]string, len(source.Toolsets))
		for j := 0; j < len(source.Toolsets); j++ {
			webSkillRequirementsDTO.Toolsets[j] = source.Toolsets[j]
		}
	}
	if source.Bins != nil {
		webSkillRequirementsDTO.Bins = make([]string, len(source.Bins))
		for k := 0; k < len(source.Bins); k++ {
			webSkillRequirementsDTO.Bins[k] = source.Bins[k]
		}
	}
	if source.Env != nil {
		webSkillRequirementsDTO.Env = make([]string, len(source.Env))
		for l := 0; l < len(source.Env); l++ {
			webSkillRequirementsDTO.Env[l] = source.Env[l]
		}
	}
	return webSkillRequirementsDTO
}
func (c *ConverterImpl) threadDTOFromDomain(source app.Thread) ThreadDTO {
	var webThreadDTO ThreadDTO
	webThreadDTO.ID = source.ID
	webThreadDTO.Title = source.Title
	webThreadDTO.WorkspaceRoot = source.WorkspaceRoot
	webThreadDTO.CreatedAt = TimeToTime(source.CreatedAt)
	webThreadDTO.UpdatedAt = TimeToTime(source.UpdatedAt)
	webThreadDTO.LatestRunID = source.LatestRunID
	webThreadDTO.State = source.State
	return webThreadDTO
}
func (c *ConverterImpl) threadDTOsFromDomain(source []app.Thread) []ThreadDTO {
	var webThreadDTOList []ThreadDTO
	if source != nil {
		webThreadDTOList = make([]ThreadDTO, len(source))
		for i := 0; i < len(source); i++ {
			webThreadDTOList[i] = c.threadDTOFromDomain(source[i])
		}
	}
	return webThreadDTOList
}
func (c *ConverterImpl) workingCheckpointDTOFromView(source *app.WorkingCheckpointView) *WorkingCheckpointDTO {
	var pWebWorkingCheckpointDTO *WorkingCheckpointDTO
	if source != nil {
		var webWorkingCheckpointDTO WorkingCheckpointDTO
		webWorkingCheckpointDTO.ThreadID = (*source).ThreadID
		webWorkingCheckpointDTO.Content = (*source).Content
		webWorkingCheckpointDTO.RelatedSkillID = (*source).RelatedSkillID
		webWorkingCheckpointDTO.UpdatedAt = TimeToTime((*source).UpdatedAt)
		pWebWorkingCheckpointDTO = &webWorkingCheckpointDTO
	}
	return pWebWorkingCheckpointDTO
}
