//go:build !goverter

package web

// DefaultConverter is the package-level converter instance generated by goverter.
// It lives behind the same build constraint as converter_gen.go so goverter can
// load converter.go without requiring the generated implementation first.
var DefaultConverter Converter = &ConverterImpl{}
