package web

import (
	"time"

	"github.com/ycvk/acorn/internal/app"
	"github.com/ycvk/acorn/internal/decision"
	"github.com/ycvk/acorn/internal/memorymodule"
	"github.com/ycvk/acorn/internal/model"
	"github.com/ycvk/acorn/internal/skills"
)

// TimeToTime passes time.Time through directly. Used by goverter to avoid
// reflection errors on time.Time's unexported fields.
func TimeToTime(t time.Time) time.Time {
	return t
}

//go:generate go tool goverter gen .

// Converter defines the mapping contract between app-layer/domain types and web-layer DTOs.
// Implementations are generated by github.com/jmattheis/goverter.
//
// goverter:converter
// goverter:output:file ./converter_gen.go
// goverter:output:format struct
// goverter:extend TimeToTime
type Converter interface {
	// Thread
	threadDTOFromDomain(source app.Thread) ThreadDTO
	threadDTOsFromDomain(source []app.Thread) []ThreadDTO

	// Message
	messageDTOFromDomain(source app.Message) MessageDTO
	messageDTOsFromDomain(source []app.Message) []MessageDTO
	disclosureItemDTOsFromDomain(source []app.DisclosureItem) []DisclosureItemDTO
	decisionOptionDTOsFromDomain(source []app.DecisionOption) []DecisionOptionDTO

	// Run
	runSummaryDTOsFromDomain(source []app.RunSummary) []RunSummaryDTO

	// Pending Action
	pendingActionOptionDTOsFromDomain(source []app.PendingActionOption) []PendingActionOptionDTO
	pendingActionSummaryDTOsFromDomain(source []app.PendingActionSummary) []PendingActionSummaryDTO

	// System / Capabilities
	capabilitiesSummaryDTOFromSnapshot(source app.SystemCapabilitySummary) CapabilitiesSummaryDTO
	capabilitiesModelDTOFromSnapshot(source app.SystemModelCapabilities) CapabilitiesModelDTO
	capabilitiesFeaturesDTOFromSnapshot(source app.SystemFeatureCapabilities) CapabilitiesFeaturesDTO
	providerReadinessDTOsFromSnapshot(source []app.ProviderReadinessSummary) []ProviderReadinessDTO
	capabilitiesToolsDTOFromSnapshot(source []app.SystemToolCapability) []CapabilitiesToolDTO

	// Memory
	memoryRecordRelationDTOsFromDomain(source []memorymodule.RecordRelation) []MemoryRecordRelationDTO
	//goverter:map RelPath Path
	memoryRecordDTOFromDomain(source memorymodule.Record) MemoryRecordDTO
	memoryRecordDTOsFromDomain(source []memorymodule.Record) []MemoryRecordDTO
	memorySearchItemDTOsFromDomain(source []memorymodule.SearchItem) []MemorySearchItemDTO
	workingCheckpointDTOFromView(source *app.WorkingCheckpointView) *WorkingCheckpointDTO

	// Workbench / Workspace
	workspaceGitStatusDTOFromDomain(source app.WorkspaceGitStatus) WorkspaceGitStatusDTO
	subagentRunDTOsFromDomain(source []app.SubagentRun) []SubagentRunDTO
	mutationCheckpointDTOsFromDomain(source []app.MutationCheckpointSummary) []MutationCheckpointDTO
	rollbackSummaryDTOsFromDomain(source []app.RollbackSummary) []RollbackSummaryDTO
	artifactSummaryDTOsFromDomain(source []app.ArtifactSummary) []ArtifactSummaryDTO

	// Context Economy
	contextEconomyDTOFromDomain(source app.ContextEconomySummary) ContextEconomyDTO

	// Provider Usage
	providerUsageDTOFromDomain(source app.ProviderUsageSummary) ProviderUsageDTO

	// Plan
	planRepoTargetDTOsFromRuntime(source []model.PlanRepoTarget) []PlanRepoTargetDTO
	verificationIntentDTOsFromRuntime(source []model.VerificationIntent) []VerificationIntentDTO

	// Skills
	skillRequirementsDTOFromDomain(source skills.Requirements) SkillRequirementsDTO

	// Decision
	runDecisionDTOFromDomain(source *decision.Record) *RunDecisionDTO
}
