// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package api

import (
	memory "github.com/ycvk/acorn/internal/memory"
	skills "github.com/ycvk/acorn/internal/skills"
)

type ConverterImpl struct{}

func (c *ConverterImpl) appArtifactSummaryToApiArtifactSummaryDTO(source ArtifactSummary) ArtifactSummaryDTO {
	var apiArtifactSummaryDTO ArtifactSummaryDTO
	apiArtifactSummaryDTO.ArtifactID = source.ArtifactID
	apiArtifactSummaryDTO.RunID = source.RunID
	apiArtifactSummaryDTO.SessionID = source.SessionID
	apiArtifactSummaryDTO.SourceToolResultRef = source.SourceToolResultRef
	apiArtifactSummaryDTO.Kind = source.Kind
	apiArtifactSummaryDTO.Title = source.Title
	apiArtifactSummaryDTO.MIMEType = source.MIMEType
	apiArtifactSummaryDTO.SizeBytes = source.SizeBytes
	apiArtifactSummaryDTO.SHA256 = source.SHA256
	apiArtifactSummaryDTO.CreatedAt = TimeToTime(source.CreatedAt)
	return apiArtifactSummaryDTO
}
func (c *ConverterImpl) appDecisionOptionToApiDecisionOptionDTO(source DecisionOption) DecisionOptionDTO {
	var apiDecisionOptionDTO DecisionOptionDTO
	apiDecisionOptionDTO.ID = source.ID
	apiDecisionOptionDTO.Label = source.Label
	apiDecisionOptionDTO.Description = source.Description
	return apiDecisionOptionDTO
}
func (c *ConverterImpl) appDisclosureItemToApiDisclosureItemDTO(source DisclosureItem) DisclosureItemDTO {
	var apiDisclosureItemDTO DisclosureItemDTO
	apiDisclosureItemDTO.Kind = source.Kind
	apiDisclosureItemDTO.Label = source.Label
	apiDisclosureItemDTO.Detail = source.Detail
	apiDisclosureItemDTO.Tone = source.Tone
	apiDisclosureItemDTO.SkillID = source.SkillID
	return apiDisclosureItemDTO
}
func (c *ConverterImpl) appMessageContentToApiMessageContentDTO(source MessageContent) MessageContentDTO {
	var apiMessageContentDTO MessageContentDTO
	apiMessageContentDTO.Type = source.Type
	apiMessageContentDTO.Text = source.Text
	if source.Parts != nil {
		apiMessageContentDTO.Parts = make([]MessagePartDTO, len(source.Parts))
		for i := 0; i < len(source.Parts); i++ {
			apiMessageContentDTO.Parts[i] = c.appMessagePartToApiMessagePartDTO(source.Parts[i])
		}
	}
	return apiMessageContentDTO
}
func (c *ConverterImpl) appMessagePartToApiMessagePartDTO(source MessagePart) MessagePartDTO {
	var apiMessagePartDTO MessagePartDTO
	apiMessagePartDTO.Kind = source.Kind
	apiMessagePartDTO.Text = source.Text
	apiMessagePartDTO.Reasoning = source.Reasoning
	apiMessagePartDTO.Status = source.Status
	apiMessagePartDTO.Title = source.Title
	apiMessagePartDTO.Summary = source.Summary
	if source.Changed != nil {
		apiMessagePartDTO.Changed = make([]string, len(source.Changed))
		for i := 0; i < len(source.Changed); i++ {
			apiMessagePartDTO.Changed[i] = source.Changed[i]
		}
	}
	if source.Verified != nil {
		apiMessagePartDTO.Verified = make([]string, len(source.Verified))
		for j := 0; j < len(source.Verified); j++ {
			apiMessagePartDTO.Verified[j] = source.Verified[j]
		}
	}
	if source.Risks != nil {
		apiMessagePartDTO.Risks = make([]string, len(source.Risks))
		for k := 0; k < len(source.Risks); k++ {
			apiMessagePartDTO.Risks[k] = source.Risks[k]
		}
	}
	apiMessagePartDTO.Items = c.disclosureItemDTOsFromDomain(source.Items)
	apiMessagePartDTO.DetailRunID = source.DetailRunID
	apiMessagePartDTO.RunID = source.RunID
	apiMessagePartDTO.Label = source.Label
	apiMessagePartDTO.DecisionID = source.DecisionID
	apiMessagePartDTO.Question = source.Question
	apiMessagePartDTO.SelectedOptionID = source.SelectedOptionID
	apiMessagePartDTO.Answer = source.Answer
	apiMessagePartDTO.Options = c.decisionOptionDTOsFromDomain(source.Options)
	apiMessagePartDTO.Action = c.pAppMessageActionToPApiMessageActionDTO(source.Action)
	return apiMessagePartDTO
}
func (c *ConverterImpl) appPendingActionOptionToApiPendingActionOptionDTO(source PendingActionOption) PendingActionOptionDTO {
	var apiPendingActionOptionDTO PendingActionOptionDTO
	apiPendingActionOptionDTO.ID = source.ID
	apiPendingActionOptionDTO.Label = source.Label
	apiPendingActionOptionDTO.Description = source.Description
	return apiPendingActionOptionDTO
}
func (c *ConverterImpl) appPendingActionSummaryToApiPendingActionSummaryDTO(source PendingActionSummary) PendingActionSummaryDTO {
	var apiPendingActionSummaryDTO PendingActionSummaryDTO
	apiPendingActionSummaryDTO.ActionID = source.ActionID
	apiPendingActionSummaryDTO.RunID = source.RunID
	apiPendingActionSummaryDTO.ThreadID = source.ThreadID
	apiPendingActionSummaryDTO.Kind = source.Kind
	apiPendingActionSummaryDTO.Status = source.Status
	apiPendingActionSummaryDTO.Title = source.Title
	apiPendingActionSummaryDTO.Body = source.Body
	apiPendingActionSummaryDTO.Options = c.pendingActionOptionDTOsFromDomain(source.Options)
	apiPendingActionSummaryDTO.CreatedAt = TimeToTime(source.CreatedAt)
	return apiPendingActionSummaryDTO
}
func (c *ConverterImpl) appProviderReadinessSummaryToApiProviderReadinessDTO(source ProviderReadinessSummary) ProviderReadinessDTO {
	var apiProviderReadinessDTO ProviderReadinessDTO
	apiProviderReadinessDTO.Scope = source.Scope
	apiProviderReadinessDTO.Provider = source.Provider
	apiProviderReadinessDTO.Status = string(source.Status)
	apiProviderReadinessDTO.Reason = source.Reason
	apiProviderReadinessDTO.StartupStatus = source.StartupStatus
	apiProviderReadinessDTO.AuthStatus = source.AuthStatus
	return apiProviderReadinessDTO
}
func (c *ConverterImpl) appRunSummaryToApiRunSummaryDTO(source RunSummary) RunSummaryDTO {
	var apiRunSummaryDTO RunSummaryDTO
	apiRunSummaryDTO.RunID = source.RunID
	apiRunSummaryDTO.ThreadID = source.ThreadID
	apiRunSummaryDTO.ThreadTitle = source.ThreadTitle
	apiRunSummaryDTO.Status = source.Status
	apiRunSummaryDTO.Mode = source.Mode
	apiRunSummaryDTO.Preview = source.Preview
	apiRunSummaryDTO.LastEventLabel = source.LastEventLabel
	apiRunSummaryDTO.AttentionLevel = source.AttentionLevel
	apiRunSummaryDTO.DurationMS = source.DurationMS
	apiRunSummaryDTO.CreatedAt = TimeToTime(source.CreatedAt)
	apiRunSummaryDTO.UpdatedAt = TimeToTime(source.UpdatedAt)
	return apiRunSummaryDTO
}
func (c *ConverterImpl) appSystemToolCapabilityToApiCapabilitiesToolDTO(source SystemToolCapability) CapabilitiesToolDTO {
	var apiCapabilitiesToolDTO CapabilitiesToolDTO
	apiCapabilitiesToolDTO.Name = source.Name
	apiCapabilitiesToolDTO.Source = source.Source
	apiCapabilitiesToolDTO.Kind = source.Kind
	apiCapabilitiesToolDTO.Category = source.Category
	apiCapabilitiesToolDTO.Enabled = source.Enabled
	apiCapabilitiesToolDTO.HealthState = source.HealthState
	apiCapabilitiesToolDTO.HealthReason = source.HealthReason
	apiCapabilitiesToolDTO.ParallelPolicy = source.ParallelPolicy
	apiCapabilitiesToolDTO.Risk = source.Risk
	apiCapabilitiesToolDTO.RootDir = source.RootDir
	apiCapabilitiesToolDTO.WorkDir = source.WorkDir
	apiCapabilitiesToolDTO.DefaultTimeout = source.DefaultTimeout
	return apiCapabilitiesToolDTO
}
func (c *ConverterImpl) artifactSummaryDTOsFromDomain(source []ArtifactSummary) []ArtifactSummaryDTO {
	var apiArtifactSummaryDTOList []ArtifactSummaryDTO
	if source != nil {
		apiArtifactSummaryDTOList = make([]ArtifactSummaryDTO, len(source))
		for i := 0; i < len(source); i++ {
			apiArtifactSummaryDTOList[i] = c.appArtifactSummaryToApiArtifactSummaryDTO(source[i])
		}
	}
	return apiArtifactSummaryDTOList
}
func (c *ConverterImpl) capabilitiesFeaturesDTOFromSnapshot(source SystemFeatureCapabilities) CapabilitiesFeaturesDTO {
	var apiCapabilitiesFeaturesDTO CapabilitiesFeaturesDTO
	apiCapabilitiesFeaturesDTO.InterruptResume = source.InterruptResume
	apiCapabilitiesFeaturesDTO.SessionHistory = source.SessionHistory
	return apiCapabilitiesFeaturesDTO
}
func (c *ConverterImpl) capabilitiesModelDTOFromSnapshot(source SystemModelCapabilities) CapabilitiesModelDTO {
	var apiCapabilitiesModelDTO CapabilitiesModelDTO
	apiCapabilitiesModelDTO.Name = source.Name
	return apiCapabilitiesModelDTO
}
func (c *ConverterImpl) capabilitiesSummaryDTOFromSnapshot(source SystemCapabilitySummary) CapabilitiesSummaryDTO {
	var apiCapabilitiesSummaryDTO CapabilitiesSummaryDTO
	apiCapabilitiesSummaryDTO.ToolCount = source.ToolCount
	apiCapabilitiesSummaryDTO.EnabledToolCount = source.EnabledToolCount
	apiCapabilitiesSummaryDTO.SkillCount = source.SkillCount
	apiCapabilitiesSummaryDTO.EligibleSkillCount = source.EligibleSkillCount
	apiCapabilitiesSummaryDTO.IneligibleSkillCount = source.IneligibleSkillCount
	apiCapabilitiesSummaryDTO.InvalidSkillCount = source.InvalidSkillCount
	apiCapabilitiesSummaryDTO.MCPConfiguredProviderCount = source.MCPConfiguredProviderCount
	apiCapabilitiesSummaryDTO.MCPEnabledProviderCount = source.MCPEnabledProviderCount
	apiCapabilitiesSummaryDTO.MCPHealthyProviderCount = source.MCPHealthyProviderCount
	return apiCapabilitiesSummaryDTO
}
func (c *ConverterImpl) capabilitiesToolsDTOFromSnapshot(source []SystemToolCapability) []CapabilitiesToolDTO {
	var apiCapabilitiesToolDTOList []CapabilitiesToolDTO
	if source != nil {
		apiCapabilitiesToolDTOList = make([]CapabilitiesToolDTO, len(source))
		for i := 0; i < len(source); i++ {
			apiCapabilitiesToolDTOList[i] = c.appSystemToolCapabilityToApiCapabilitiesToolDTO(source[i])
		}
	}
	return apiCapabilitiesToolDTOList
}
func (c *ConverterImpl) decisionOptionDTOsFromDomain(source []DecisionOption) []DecisionOptionDTO {
	var apiDecisionOptionDTOList []DecisionOptionDTO
	if source != nil {
		apiDecisionOptionDTOList = make([]DecisionOptionDTO, len(source))
		for i := 0; i < len(source); i++ {
			apiDecisionOptionDTOList[i] = c.appDecisionOptionToApiDecisionOptionDTO(source[i])
		}
	}
	return apiDecisionOptionDTOList
}
func (c *ConverterImpl) disclosureItemDTOsFromDomain(source []DisclosureItem) []DisclosureItemDTO {
	var apiDisclosureItemDTOList []DisclosureItemDTO
	if source != nil {
		apiDisclosureItemDTOList = make([]DisclosureItemDTO, len(source))
		for i := 0; i < len(source); i++ {
			apiDisclosureItemDTOList[i] = c.appDisclosureItemToApiDisclosureItemDTO(source[i])
		}
	}
	return apiDisclosureItemDTOList
}
func (c *ConverterImpl) memoryRecordDTOFromDomain(source memory.Record) MemoryRecordDTO {
	var apiMemoryRecordDTO MemoryRecordDTO
	apiMemoryRecordDTO.Ref = source.Ref
	apiMemoryRecordDTO.Kind = string(source.Kind)
	apiMemoryRecordDTO.Title = source.Title
	apiMemoryRecordDTO.Status = string(source.Status)
	apiMemoryRecordDTO.Scope = source.Scope
	if source.Tags != nil {
		apiMemoryRecordDTO.Tags = make([]string, len(source.Tags))
		for i := 0; i < len(source.Tags); i++ {
			apiMemoryRecordDTO.Tags[i] = source.Tags[i]
		}
	}
	apiMemoryRecordDTO.Origin = source.Origin
	apiMemoryRecordDTO.TaskPattern = source.TaskPattern
	apiMemoryRecordDTO.Path = source.RelPath
	apiMemoryRecordDTO.Body = source.Body
	apiMemoryRecordDTO.Created = source.Created
	apiMemoryRecordDTO.Updated = source.Updated
	apiMemoryRecordDTO.SourceRun = source.SourceRun
	if source.SourceRefs != nil {
		apiMemoryRecordDTO.SourceRefs = make([]string, len(source.SourceRefs))
		for j := 0; j < len(source.SourceRefs); j++ {
			apiMemoryRecordDTO.SourceRefs[j] = source.SourceRefs[j]
		}
	}
	return apiMemoryRecordDTO
}
func (c *ConverterImpl) memoryRecordDTOsFromDomain(source []memory.Record) []MemoryRecordDTO {
	var apiMemoryRecordDTOList []MemoryRecordDTO
	if source != nil {
		apiMemoryRecordDTOList = make([]MemoryRecordDTO, len(source))
		for i := 0; i < len(source); i++ {
			apiMemoryRecordDTOList[i] = c.memoryRecordDTOFromDomain(source[i])
		}
	}
	return apiMemoryRecordDTOList
}
func (c *ConverterImpl) memorySearchItemDTOsFromDomain(source []memory.SearchItem) []MemorySearchItemDTO {
	var apiMemorySearchItemDTOList []MemorySearchItemDTO
	if source != nil {
		apiMemorySearchItemDTOList = make([]MemorySearchItemDTO, len(source))
		for i := 0; i < len(source); i++ {
			apiMemorySearchItemDTOList[i] = c.memorySearchItemToApiMemorySearchItemDTO(source[i])
		}
	}
	return apiMemorySearchItemDTOList
}
func (c *ConverterImpl) memorySearchItemToApiMemorySearchItemDTO(source memory.SearchItem) MemorySearchItemDTO {
	var apiMemorySearchItemDTO MemorySearchItemDTO
	apiMemorySearchItemDTO.Ref = source.Ref
	apiMemorySearchItemDTO.Kind = source.Kind
	apiMemorySearchItemDTO.Title = source.Title
	apiMemorySearchItemDTO.Status = source.Status
	apiMemorySearchItemDTO.Scope = source.Scope
	if source.Tags != nil {
		apiMemorySearchItemDTO.Tags = make([]string, len(source.Tags))
		for i := 0; i < len(source.Tags); i++ {
			apiMemorySearchItemDTO.Tags[i] = source.Tags[i]
		}
	}
	apiMemorySearchItemDTO.Origin = source.Origin
	apiMemorySearchItemDTO.TaskPattern = source.TaskPattern
	apiMemorySearchItemDTO.Path = source.Path
	apiMemorySearchItemDTO.Snippet = source.Snippet
	apiMemorySearchItemDTO.Score = source.Score
	apiMemorySearchItemDTO.Created = source.Created
	apiMemorySearchItemDTO.Updated = source.Updated
	apiMemorySearchItemDTO.SourceRun = source.SourceRun
	if source.SourceRefs != nil {
		apiMemorySearchItemDTO.SourceRefs = make([]string, len(source.SourceRefs))
		for j := 0; j < len(source.SourceRefs); j++ {
			apiMemorySearchItemDTO.SourceRefs[j] = source.SourceRefs[j]
		}
	}
	return apiMemorySearchItemDTO
}
func (c *ConverterImpl) messageDTOFromDomain(source Message) MessageDTO {
	var apiMessageDTO MessageDTO
	apiMessageDTO.ID = source.ID
	apiMessageDTO.ThreadID = source.ThreadID
	apiMessageDTO.Role = source.Role
	apiMessageDTO.Content = c.appMessageContentToApiMessageContentDTO(source.Content)
	apiMessageDTO.CreatedAt = TimeToTime(source.CreatedAt)
	apiMessageDTO.RunID = source.RunID
	return apiMessageDTO
}
func (c *ConverterImpl) messageDTOsFromDomain(source []Message) []MessageDTO {
	var apiMessageDTOList []MessageDTO
	if source != nil {
		apiMessageDTOList = make([]MessageDTO, len(source))
		for i := 0; i < len(source); i++ {
			apiMessageDTOList[i] = c.messageDTOFromDomain(source[i])
		}
	}
	return apiMessageDTOList
}
func (c *ConverterImpl) pAppMessageActionToPApiMessageActionDTO(source *MessageAction) *MessageActionDTO {
	var pApiMessageActionDTO *MessageActionDTO
	if source != nil {
		var apiMessageActionDTO MessageActionDTO
		apiMessageActionDTO.Kind = (*source).Kind
		apiMessageActionDTO.RunID = (*source).RunID
		apiMessageActionDTO.Label = (*source).Label
		pApiMessageActionDTO = &apiMessageActionDTO
	}
	return pApiMessageActionDTO
}
func (c *ConverterImpl) pendingActionOptionDTOsFromDomain(source []PendingActionOption) []PendingActionOptionDTO {
	var apiPendingActionOptionDTOList []PendingActionOptionDTO
	if source != nil {
		apiPendingActionOptionDTOList = make([]PendingActionOptionDTO, len(source))
		for i := 0; i < len(source); i++ {
			apiPendingActionOptionDTOList[i] = c.appPendingActionOptionToApiPendingActionOptionDTO(source[i])
		}
	}
	return apiPendingActionOptionDTOList
}
func (c *ConverterImpl) pendingActionSummaryDTOsFromDomain(source []PendingActionSummary) []PendingActionSummaryDTO {
	var apiPendingActionSummaryDTOList []PendingActionSummaryDTO
	if source != nil {
		apiPendingActionSummaryDTOList = make([]PendingActionSummaryDTO, len(source))
		for i := 0; i < len(source); i++ {
			apiPendingActionSummaryDTOList[i] = c.appPendingActionSummaryToApiPendingActionSummaryDTO(source[i])
		}
	}
	return apiPendingActionSummaryDTOList
}
func (c *ConverterImpl) providerReadinessDTOsFromSnapshot(source []ProviderReadinessSummary) []ProviderReadinessDTO {
	var apiProviderReadinessDTOList []ProviderReadinessDTO
	if source != nil {
		apiProviderReadinessDTOList = make([]ProviderReadinessDTO, len(source))
		for i := 0; i < len(source); i++ {
			apiProviderReadinessDTOList[i] = c.appProviderReadinessSummaryToApiProviderReadinessDTO(source[i])
		}
	}
	return apiProviderReadinessDTOList
}
func (c *ConverterImpl) runSummaryDTOsFromDomain(source []RunSummary) []RunSummaryDTO {
	var apiRunSummaryDTOList []RunSummaryDTO
	if source != nil {
		apiRunSummaryDTOList = make([]RunSummaryDTO, len(source))
		for i := 0; i < len(source); i++ {
			apiRunSummaryDTOList[i] = c.appRunSummaryToApiRunSummaryDTO(source[i])
		}
	}
	return apiRunSummaryDTOList
}
func (c *ConverterImpl) skillRequirementsDTOFromDomain(source skills.Requirements) SkillRequirementsDTO {
	var apiSkillRequirementsDTO SkillRequirementsDTO
	if source.Tools != nil {
		apiSkillRequirementsDTO.Tools = make([]string, len(source.Tools))
		for i := 0; i < len(source.Tools); i++ {
			apiSkillRequirementsDTO.Tools[i] = source.Tools[i]
		}
	}
	if source.Toolsets != nil {
		apiSkillRequirementsDTO.Toolsets = make([]string, len(source.Toolsets))
		for j := 0; j < len(source.Toolsets); j++ {
			apiSkillRequirementsDTO.Toolsets[j] = source.Toolsets[j]
		}
	}
	if source.Bins != nil {
		apiSkillRequirementsDTO.Bins = make([]string, len(source.Bins))
		for k := 0; k < len(source.Bins); k++ {
			apiSkillRequirementsDTO.Bins[k] = source.Bins[k]
		}
	}
	if source.Env != nil {
		apiSkillRequirementsDTO.Env = make([]string, len(source.Env))
		for l := 0; l < len(source.Env); l++ {
			apiSkillRequirementsDTO.Env[l] = source.Env[l]
		}
	}
	return apiSkillRequirementsDTO
}
func (c *ConverterImpl) threadDTOFromDomain(source Thread) ThreadDTO {
	var apiThreadDTO ThreadDTO
	apiThreadDTO.ID = source.ID
	apiThreadDTO.Title = source.Title
	apiThreadDTO.WorkspaceRoot = source.WorkspaceRoot
	apiThreadDTO.CreatedAt = TimeToTime(source.CreatedAt)
	apiThreadDTO.UpdatedAt = TimeToTime(source.UpdatedAt)
	apiThreadDTO.LatestRunID = source.LatestRunID
	apiThreadDTO.State = source.State
	return apiThreadDTO
}
func (c *ConverterImpl) threadDTOsFromDomain(source []Thread) []ThreadDTO {
	var apiThreadDTOList []ThreadDTO
	if source != nil {
		apiThreadDTOList = make([]ThreadDTO, len(source))
		for i := 0; i < len(source); i++ {
			apiThreadDTOList[i] = c.threadDTOFromDomain(source[i])
		}
	}
	return apiThreadDTOList
}
