package api

import (
	"time"

	"github.com/ycvk/acorn/internal/skills"
)

// TimeToTime passes time.Time through directly. Used by goverter to avoid
// reflection errors on time.Time's unexported fields.
func TimeToTime(t time.Time) time.Time {
	return t
}

//go:generate go tool goverter gen .

// Converter defines the mapping contract between app-layer/domain types and web-layer DTOs.
// Implementations are generated by github.com/jmattheis/goverter.
//
// goverter:converter
// goverter:output:file ./converter_gen.go
// goverter:output:format struct
// goverter:extend TimeToTime
type Converter interface {
	// Thread
	threadDTOFromDomain(source Thread) ThreadDTO
	threadDTOsFromDomain(source []Thread) []ThreadDTO

	// Message
	messageDTOFromDomain(source Message) MessageDTO
	messageDTOsFromDomain(source []Message) []MessageDTO

	// Run
	runSummaryDTOsFromDomain(source []RunSummary) []RunSummaryDTO

	// Pending Action
	pendingActionOptionDTOsFromDomain(source []PendingActionOption) []PendingActionOptionDTO
	pendingActionSummaryDTOsFromDomain(source []PendingActionSummary) []PendingActionSummaryDTO

	// System / Capabilities
	capabilitiesSummaryDTOFromSnapshot(source SystemCapabilitySummary) CapabilitiesSummaryDTO
	capabilitiesModelDTOFromSnapshot(source SystemModelCapabilities) CapabilitiesModelDTO
	capabilitiesFeaturesDTOFromSnapshot(source SystemFeatureCapabilities) CapabilitiesFeaturesDTO
	providerReadinessDTOsFromSnapshot(source []ProviderReadinessSummary) []ProviderReadinessDTO
	capabilitiesToolsDTOFromSnapshot(source []SystemToolCapability) []CapabilitiesToolDTO

	// Artifacts
	artifactSummaryDTOsFromDomain(source []ArtifactSummary) []ArtifactSummaryDTO

	// Skills
	skillRequirementsDTOFromDomain(source skills.Requirements) SkillRequirementsDTO
}
