/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param toolCount 
 * @param enabledToolCount 
 * @param skillCount 
 * @param eligibleSkillCount 
 * @param ineligibleSkillCount 
 * @param invalidSkillCount 
 * @param mcpConfiguredProviderCount 
 * @param mcpEnabledProviderCount 
 * @param mcpHealthyProviderCount 
 */


data class CapabilitiesSummary (

    @Json(name = "tool_count")
    val toolCount: kotlin.Int,

    @Json(name = "enabled_tool_count")
    val enabledToolCount: kotlin.Int,

    @Json(name = "skill_count")
    val skillCount: kotlin.Int,

    @Json(name = "eligible_skill_count")
    val eligibleSkillCount: kotlin.Int,

    @Json(name = "ineligible_skill_count")
    val ineligibleSkillCount: kotlin.Int,

    @Json(name = "invalid_skill_count")
    val invalidSkillCount: kotlin.Int,

    @Json(name = "mcp_configured_provider_count")
    val mcpConfiguredProviderCount: kotlin.Int,

    @Json(name = "mcp_enabled_provider_count")
    val mcpEnabledProviderCount: kotlin.Int,

    @Json(name = "mcp_healthy_provider_count")
    val mcpHealthyProviderCount: kotlin.Int

) {


}

