/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name 
 * @param source 
 * @param kind 
 * @param category 
 * @param enabled 
 * @param healthState 
 * @param risk 
 * @param resourceScope 
 * @param profiles 
 * @param healthReason 
 * @param parallelPolicy 
 * @param planPolicy 
 * @param rootDir 
 * @param workDir 
 * @param defaultTimeout 
 */


data class CapabilitiesTool (

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "source")
    val source: kotlin.String,

    @Json(name = "kind")
    val kind: kotlin.String,

    @Json(name = "category")
    val category: kotlin.String,

    @Json(name = "enabled")
    val enabled: kotlin.Boolean,

    @Json(name = "health_state")
    val healthState: kotlin.String,

    @Json(name = "risk")
    val risk: kotlin.String,

    @Json(name = "resource_scope")
    val resourceScope: kotlin.String? = null,

    @Json(name = "profiles")
    val profiles: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "health_reason")
    val healthReason: kotlin.String? = null,

    @Json(name = "parallel_policy")
    val parallelPolicy: kotlin.String? = null,

    @Json(name = "plan_policy")
    val planPolicy: kotlin.String? = null,

    @Json(name = "root_dir")
    val rootDir: kotlin.String? = null,

    @Json(name = "work_dir")
    val workDir: kotlin.String? = null,

    @Json(name = "default_timeout")
    val defaultTimeout: kotlin.Int? = null

) {


}

