/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.models

import io.ycvk.acorn.api.models.ClientProviderSettings
import io.ycvk.acorn.api.models.ClientRuntimeSettings
import io.ycvk.acorn.api.models.ClientWebSettings

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param workspaceRoot 
 * @param providers 
 * @param runtime 
 * @param web 
 * @param configPath 
 * @param configDir 
 */


data class ClientSettings (

    @Json(name = "workspace_root")
    val workspaceRoot: kotlin.String,

    @Json(name = "providers")
    val providers: kotlin.collections.List<ClientProviderSettings>,

    @Json(name = "runtime")
    val runtime: ClientRuntimeSettings,

    @Json(name = "web")
    val web: ClientWebSettings,

    @Json(name = "config_path")
    val configPath: kotlin.String? = null,

    @Json(name = "config_dir")
    val configDir: kotlin.String? = null

) {


}

