/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name 
 * @param model 
 * @param enabled 
 * @param baseUrl 
 * @param timeoutSeconds 
 * @param temperature 
 * @param maxCompletionTokens 
 * @param reasoningEffort Controls reasoning model effort (low=fastest, medium=default, high=most thorough). Only used by reasoning-capable models (o1, o3, etc.).
 * @param extraFields Provider-specific extra body fields added to the top-level of the API request. Useful for vendor-specific features not covered by standard fields. Examples — Claude thinking mode (nested object with 'type' and 'budget_tokens'), or other provider extensions. Fields must match the provider API schema exactly.
 */


data class ClientProviderSettings (

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "model")
    val model: kotlin.String,

    @Json(name = "enabled")
    val enabled: kotlin.Boolean,

    @Json(name = "base_url")
    val baseUrl: kotlin.String? = null,

    @Json(name = "timeout_seconds")
    val timeoutSeconds: kotlin.Int? = null,

    @Json(name = "temperature")
    val temperature: kotlin.Float? = null,

    @Json(name = "max_completion_tokens")
    val maxCompletionTokens: kotlin.Int? = null,

    /* Controls reasoning model effort (low=fastest, medium=default, high=most thorough). Only used by reasoning-capable models (o1, o3, etc.). */
    @Json(name = "reasoning_effort")
    val reasoningEffort: ClientProviderSettings.ReasoningEffort? = null,

    /* Provider-specific extra body fields added to the top-level of the API request. Useful for vendor-specific features not covered by standard fields. Examples — Claude thinking mode (nested object with 'type' and 'budget_tokens'), or other provider extensions. Fields must match the provider API schema exactly. */
    @Json(name = "extra_fields")
    val extraFields: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

) {

    /**
     * Controls reasoning model effort (low=fastest, medium=default, high=most thorough). Only used by reasoning-capable models (o1, o3, etc.).
     *
     * Values: low,medium,high
     */
    @JsonClass(generateAdapter = false)
    enum class ReasoningEffort(val value: kotlin.String) {
        @Json(name = "low") low("low"),
        @Json(name = "medium") medium("medium"),
        @Json(name = "high") high("high");
    }

}

