/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param skillId 
 * @param mode 
 * @param input Optional run input. When set, the run records it as the pending user message in one step, so a separate POST /messages is not required.
 */


data class CreateRunRequest (

    @Json(name = "skill_id")
    val skillId: kotlin.String? = null,

    @Json(name = "mode")
    val mode: CreateRunRequest.Mode? = null,

    /* Optional run input. When set, the run records it as the pending user message in one step, so a separate POST /messages is not required. */
    @Json(name = "input")
    val input: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: direct_response,plan_execute
     */
    @JsonClass(generateAdapter = false)
    enum class Mode(val value: kotlin.String) {
        @Json(name = "direct_response") direct_response("direct_response"),
        @Json(name = "plan_execute") plan_execute("plan_execute");
    }

}

