/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param decision 
 * @param selectedOptionId 
 * @param answer 
 */


data class DecidePendingActionRequest (

    @Json(name = "decision")
    val decision: DecidePendingActionRequest.Decision,

    @Json(name = "selected_option_id")
    val selectedOptionId: kotlin.String? = null,

    @Json(name = "answer")
    val answer: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: accept,decline,answer
     */
    @JsonClass(generateAdapter = false)
    enum class Decision(val value: kotlin.String) {
        @Json(name = "accept") accept("accept"),
        @Json(name = "decline") decline("decline"),
        @Json(name = "answer") answer("answer");
    }

}

