/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.models

import io.ycvk.acorn.api.models.DecisionOption

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param kind 
 * @param decisionId 
 * @param question 
 * @param status 
 * @param selectedOptionId 
 * @param answer 
 * @param options 
 */


data class DecisionMessagePart (

    @Json(name = "kind")
    val kind: DecisionMessagePart.Kind,

    @Json(name = "decision_id")
    val decisionId: kotlin.String,

    @Json(name = "question")
    val question: kotlin.String,

    @Json(name = "status")
    val status: DecisionMessagePart.Status? = null,

    @Json(name = "selected_option_id")
    val selectedOptionId: kotlin.String? = null,

    @Json(name = "answer")
    val answer: kotlin.String? = null,

    @Json(name = "options")
    val options: kotlin.collections.List<DecisionOption>? = null

) {

    /**
     * 
     *
     * Values: decision
     */
    @JsonClass(generateAdapter = false)
    enum class Kind(val value: kotlin.String) {
        @Json(name = "decision") decision("decision");
    }
    /**
     * 
     *
     * Values: pending,approved,rejected,resolved
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "pending") pending("pending"),
        @Json(name = "approved") approved("approved"),
        @Json(name = "rejected") rejected("rejected"),
        @Json(name = "resolved") resolved("resolved");
    }

}

