/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param deviceId 
 * @param name 
 * @param platform 
 * @param createdAt 
 * @param lastSeenAt 
 * @param revokedAt 
 */


data class Device (

    @Json(name = "device_id")
    val deviceId: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "platform")
    val platform: kotlin.String,

    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "last_seen_at")
    val lastSeenAt: java.time.OffsetDateTime,

    @Json(name = "revoked_at")
    val revokedAt: java.time.OffsetDateTime? = null

) {


}

