/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param kind 
 * @param label 
 * @param tone 
 * @param detail 
 * @param skillId 
 */


data class DisclosureItem (

    @Json(name = "kind")
    val kind: DisclosureItem.Kind,

    @Json(name = "label")
    val label: kotlin.String,

    @Json(name = "tone")
    val tone: DisclosureItem.Tone,

    @Json(name = "detail")
    val detail: kotlin.String? = null,

    @Json(name = "skill_id")
    val skillId: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: memory,skill
     */
    @JsonClass(generateAdapter = false)
    enum class Kind(val value: kotlin.String) {
        @Json(name = "memory") memory("memory"),
        @Json(name = "skill") skill("skill");
    }
    /**
     * 
     *
     * Values: memory,skill,procedure,neutral,warning
     */
    @JsonClass(generateAdapter = false)
    enum class Tone(val value: kotlin.String) {
        @Json(name = "memory") memory("memory"),
        @Json(name = "skill") skill("skill"),
        @Json(name = "procedure") procedure("procedure"),
        @Json(name = "neutral") neutral("neutral"),
        @Json(name = "warning") warning("warning");
    }

}

