/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.models

import io.ycvk.acorn.api.models.PendingActionSummary
import io.ycvk.acorn.api.models.RunSummary
import io.ycvk.acorn.api.models.SystemStatus

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param pendingActions 
 * @param activeRuns 
 * @param recentTerminalRuns 
 * @param system 
 */


data class InboxResponse (

    @Json(name = "pending_actions")
    val pendingActions: kotlin.collections.List<PendingActionSummary>,

    @Json(name = "active_runs")
    val activeRuns: kotlin.collections.List<RunSummary>,

    @Json(name = "recent_terminal_runs")
    val recentTerminalRuns: kotlin.collections.List<RunSummary>,

    @Json(name = "system")
    val system: SystemStatus

) {


}

