/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param path 
 * @param title 
 * @param tags 
 * @param updatedAt 
 * @param body Markdown body of the current revision.
 * @param source 
 * @param createdAt 
 */


data class KnowledgeNote (

    @Json(name = "path")
    val path: kotlin.String,

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "tags")
    val tags: kotlin.collections.List<kotlin.String>,

    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    /* Markdown body of the current revision. */
    @Json(name = "body")
    val body: kotlin.String,

    @Json(name = "source")
    val source: kotlin.String? = null,

    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime? = null

) {


}

