/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param path 
 * @param title 
 * @param tags 
 * @param snippet 
 * @param updatedAt 
 */


data class KnowledgeNoteSummary (

    @Json(name = "path")
    val path: kotlin.String,

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "tags")
    val tags: kotlin.collections.List<kotlin.String>,

    @Json(name = "snippet")
    val snippet: kotlin.String,

    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime

) {


}

