/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.models

import io.ycvk.acorn.api.models.MemoryRecordRelation

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param ref 
 * @param kind 
 * @param title 
 * @param status 
 * @param path 
 * @param body 
 * @param scope 
 * @param tags 
 * @param origin 
 * @param taskPattern 
 * @param created 
 * @param updated 
 * @param validFrom 
 * @param validUntil 
 * @param sourceRun 
 * @param sourceRefs 
 * @param evidenceRefs 
 * @param relations 
 */


data class MemoryRecord (

    @Json(name = "ref")
    val ref: kotlin.String,

    @Json(name = "kind")
    val kind: MemoryRecord.Kind,

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "status")
    val status: MemoryRecord.Status,

    @Json(name = "path")
    val path: kotlin.String,

    @Json(name = "body")
    val body: kotlin.String,

    @Json(name = "scope")
    val scope: kotlin.String? = null,

    @Json(name = "tags")
    val tags: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "origin")
    val origin: MemoryRecord.Origin? = null,

    @Json(name = "task_pattern")
    val taskPattern: kotlin.String? = null,

    @Json(name = "created")
    val created: kotlin.String? = null,

    @Json(name = "updated")
    val updated: kotlin.String? = null,

    @Json(name = "valid_from")
    val validFrom: kotlin.String? = null,

    @Json(name = "valid_until")
    val validUntil: kotlin.String? = null,

    @Json(name = "source_run")
    val sourceRun: kotlin.String? = null,

    @Json(name = "source_refs")
    val sourceRefs: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "evidence_refs")
    val evidenceRefs: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "relations")
    val relations: kotlin.collections.List<MemoryRecordRelation>? = null

) {

    /**
     * 
     *
     * Values: fact,skill,history
     */
    @JsonClass(generateAdapter = false)
    enum class Kind(val value: kotlin.String) {
        @Json(name = "fact") fact("fact"),
        @Json(name = "skill") skill("skill"),
        @Json(name = "history") history("history");
    }
    /**
     * 
     *
     * Values: unverified,verified,retired
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "unverified") unverified("unverified"),
        @Json(name = "verified") verified("verified"),
        @Json(name = "retired") retired("retired");
    }
    /**
     * 
     *
     * Values: human,agent_draft,action_verified
     */
    @JsonClass(generateAdapter = false)
    enum class Origin(val value: kotlin.String) {
        @Json(name = "human") human("human"),
        @Json(name = "agent_draft") agent_draft("agent_draft"),
        @Json(name = "action_verified") action_verified("action_verified");
    }

}

