/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 * @param target 
 * @param reason 
 */


data class MemoryRecordRelation (

    @Json(name = "type")
    val type: MemoryRecordRelation.Type,

    @Json(name = "target")
    val target: kotlin.String,

    @Json(name = "reason")
    val reason: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: supports,derived_from,supersedes,contradicts
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "supports") supports("supports"),
        @Json(name = "derived_from") derived_from("derived_from"),
        @Json(name = "supersedes") supersedes("supersedes"),
        @Json(name = "contradicts") contradicts("contradicts");
    }

}

