/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 * @param key 
 */


data class MemoryScope (

    @Json(name = "type")
    val type: MemoryScope.Type,

    @Json(name = "key")
    val key: kotlin.String

) {

    /**
     * 
     *
     * Values: global_user,machine,workspace,thread,run,skill,unknown
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "global_user") global_user("global_user"),
        @Json(name = "machine") machine("machine"),
        @Json(name = "workspace") workspace("workspace"),
        @Json(name = "thread") thread("thread"),
        @Json(name = "run") run("run"),
        @Json(name = "skill") skill("skill"),
        @Json(name = "unknown") unknown("unknown");
    }

}

