/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.models

import io.ycvk.acorn.api.models.MessageContent

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param threadId 
 * @param role 
 * @param content 
 * @param createdAt 
 * @param runId 
 */


data class Message (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "thread_id")
    val threadId: kotlin.String,

    @Json(name = "role")
    val role: Message.Role,

    @Json(name = "content")
    val content: MessageContent,

    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "run_id")
    val runId: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: user,assistant,system,tool
     */
    @JsonClass(generateAdapter = false)
    enum class Role(val value: kotlin.String) {
        @Json(name = "user") user("user"),
        @Json(name = "assistant") assistant("assistant"),
        @Json(name = "system") system("system"),
        @Json(name = "tool") tool("tool");
    }

}

