/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.models

import io.ycvk.acorn.api.models.DecisionMessagePart
import io.ycvk.acorn.api.models.DecisionOption
import io.ycvk.acorn.api.models.DisclosureItem
import io.ycvk.acorn.api.models.DisclosureMessagePart
import io.ycvk.acorn.api.models.MessageAction
import io.ycvk.acorn.api.models.ReasoningMessagePart
import io.ycvk.acorn.api.models.ResultMessagePart
import io.ycvk.acorn.api.models.TechnicalDetailLinkMessagePart
import io.ycvk.acorn.api.models.TextMessagePart
import io.ycvk.acorn.api.models.WorkStatusMessagePart

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param kind 
 * @param text 
 * @param reasoning 
 * @param status 
 * @param title 
 * @param summary 
 * @param decisionId 
 * @param question 
 * @param changed 
 * @param verified 
 * @param risks 
 * @param items 
 * @param runId 
 * @param label 
 * @param detailRunId 
 * @param action 
 * @param selectedOptionId 
 * @param answer 
 * @param options 
 */


interface MessagePart {

    @Json(name = "kind")
    val kind: MessagePart.Kind
    @Json(name = "text")
    val text: kotlin.String
    @Json(name = "reasoning")
    val reasoning: kotlin.String
    @Json(name = "status")
    val status: MessagePart.Status
    @Json(name = "title")
    val title: kotlin.String
    @Json(name = "summary")
    val summary: kotlin.String
    @Json(name = "decision_id")
    val decisionId: kotlin.String
    @Json(name = "question")
    val question: kotlin.String
    @Json(name = "changed")
    val changed: kotlin.collections.List<kotlin.String>
    @Json(name = "verified")
    val verified: kotlin.collections.List<kotlin.String>
    @Json(name = "risks")
    val risks: kotlin.collections.List<kotlin.String>
    @Json(name = "items")
    val items: kotlin.collections.List<DisclosureItem>
    @Json(name = "run_id")
    val runId: kotlin.String
    @Json(name = "label")
    val label: kotlin.String
    @Json(name = "detail_run_id")
    val detailRunId: kotlin.String?
    @Json(name = "action")
    val action: MessageAction?
    @Json(name = "selected_option_id")
    val selectedOptionId: kotlin.String?
    @Json(name = "answer")
    val answer: kotlin.String?
    @Json(name = "options")
    val options: kotlin.collections.List<DecisionOption>?
    /**
     * 
     *
     * Values: technical_detail_link
     */
    @JsonClass(generateAdapter = false)
    enum class Kind(val value: kotlin.String) {
        @Json(name = "technical_detail_link") technical_detail_link("technical_detail_link");
    }
    /**
     * 
     *
     * Values: pending,approved,rejected,resolved
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "pending") pending("pending"),
        @Json(name = "approved") approved("approved"),
        @Json(name = "rejected") rejected("rejected"),
        @Json(name = "resolved") resolved("resolved");
    }

}

