/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.models

import io.ycvk.acorn.api.models.NowOccurrence

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param content 
 * @param state 
 * @param wakeAt The next wake; for a due commitment, the wake that is being handled.
 * @param occurrences Wakes that have not been completed yet.
 * @param recurrence 5-field cron in the owner's timezone.
 */


data class NowCommitment (

    @Json(name = "id")
    val id: kotlin.Long,

    @Json(name = "content")
    val content: kotlin.String,

    @Json(name = "state")
    val state: NowCommitment.State,

    /* The next wake; for a due commitment, the wake that is being handled. */
    @Json(name = "wake_at")
    val wakeAt: java.time.OffsetDateTime,

    /* Wakes that have not been completed yet. */
    @Json(name = "occurrences")
    val occurrences: kotlin.collections.List<NowOccurrence>,

    /* 5-field cron in the owner's timezone. */
    @Json(name = "recurrence")
    val recurrence: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: scheduled,due
     */
    @JsonClass(generateAdapter = false)
    enum class State(val value: kotlin.String) {
        @Json(name = "scheduled") scheduled("scheduled"),
        @Json(name = "due") due("due");
    }

}

