/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param title 
 * @param state 
 * @param reason 
 * @param updatedAt 
 * @param reviewAt 
 */


data class NowConcern (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "state")
    val state: NowConcern.State,

    @Json(name = "reason")
    val reason: kotlin.String,

    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    @Json(name = "review_at")
    val reviewAt: java.time.OffsetDateTime? = null

) {

    /**
     * 
     *
     * Values: active,waiting
     */
    @JsonClass(generateAdapter = false)
    enum class State(val value: kotlin.String) {
        @Json(name = "active") active("active"),
        @Json(name = "waiting") waiting("waiting");
    }

}

