/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param dueAt 
 * @param state claimed while the wake is starting, due once its run started and until it is completed.
 * @param runId 
 */


data class NowOccurrence (

    @Json(name = "id")
    val id: kotlin.Long,

    @Json(name = "due_at")
    val dueAt: java.time.OffsetDateTime,

    /* claimed while the wake is starting, due once its run started and until it is completed. */
    @Json(name = "state")
    val state: NowOccurrence.State,

    @Json(name = "run_id")
    val runId: kotlin.String? = null

) {

    /**
     * claimed while the wake is starting, due once its run started and until it is completed.
     *
     * Values: claimed,due
     */
    @JsonClass(generateAdapter = false)
    enum class State(val value: kotlin.String) {
        @Json(name = "claimed") claimed("claimed"),
        @Json(name = "due") due("due");
    }

}

