/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.models

import io.ycvk.acorn.api.models.NowBriefing
import io.ycvk.acorn.api.models.NowCommitment
import io.ycvk.acorn.api.models.NowConcern
import io.ycvk.acorn.api.models.NowWatch

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param commitments 
 * @param concerns 
 * @param watches 
 * @param briefing 
 */


data class NowResponse (

    @Json(name = "commitments")
    val commitments: kotlin.collections.List<NowCommitment>,

    @Json(name = "concerns")
    val concerns: kotlin.collections.List<NowConcern>,

    @Json(name = "watches")
    val watches: kotlin.collections.List<NowWatch>,

    @Json(name = "briefing")
    val briefing: NowBriefing? = null

) {


}

