/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param name 
 * @param kind 
 * @param target 
 * @param mode 
 * @param status 
 * @param intervalSeconds 
 * @param nextCheckAt 
 * @param failures 
 * @param lastCheckedAt 
 * @param lastError 
 */


data class NowWatch (

    @Json(name = "id")
    val id: kotlin.Long,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "kind")
    val kind: NowWatch.Kind,

    @Json(name = "target")
    val target: kotlin.String,

    @Json(name = "mode")
    val mode: NowWatch.Mode,

    @Json(name = "status")
    val status: NowWatch.Status,

    @Json(name = "interval_seconds")
    val intervalSeconds: kotlin.Long,

    @Json(name = "next_check_at")
    val nextCheckAt: java.time.OffsetDateTime,

    @Json(name = "failures")
    val failures: kotlin.Int,

    @Json(name = "last_checked_at")
    val lastCheckedAt: java.time.OffsetDateTime? = null,

    @Json(name = "last_error")
    val lastError: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: rss,github,web,web_rendered
     */
    @JsonClass(generateAdapter = false)
    enum class Kind(val value: kotlin.String) {
        @Json(name = "rss") rss("rss"),
        @Json(name = "github") github("github"),
        @Json(name = "web") web("web"),
        @Json(name = "web_rendered") web_rendered("web_rendered");
    }
    /**
     * 
     *
     * Values: digest,immediate
     */
    @JsonClass(generateAdapter = false)
    enum class Mode(val value: kotlin.String) {
        @Json(name = "digest") digest("digest"),
        @Json(name = "immediate") immediate("immediate");
    }
    /**
     * 
     *
     * Values: active,paused,failing
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "active") active("active"),
        @Json(name = "paused") paused("paused"),
        @Json(name = "failing") failing("failing");
    }

}

