/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.models

import io.ycvk.acorn.api.models.PendingActionOption

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param actionId 
 * @param question 
 * @param options 
 * @param allowFreeform 
 * @param decision 
 * @param selectedOptionId 
 * @param answer 
 */


data class OperatorQuestionData (

    @Json(name = "action_id")
    val actionId: kotlin.String,

    @Json(name = "question")
    val question: kotlin.String? = null,

    @Json(name = "options")
    val options: kotlin.collections.List<PendingActionOption>? = null,

    @Json(name = "allow_freeform")
    val allowFreeform: kotlin.Boolean? = null,

    @Json(name = "decision")
    val decision: OperatorQuestionData.Decision? = null,

    @Json(name = "selected_option_id")
    val selectedOptionId: kotlin.String? = null,

    @Json(name = "answer")
    val answer: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: answer,decline
     */
    @JsonClass(generateAdapter = false)
    enum class Decision(val value: kotlin.String) {
        @Json(name = "answer") answer("answer"),
        @Json(name = "decline") decline("decline");
    }

}

