/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param actionId 
 * @param runId 
 * @param status 
 * @param decision 
 * @param selectedOptionId 
 * @param answer 
 * @param decidedAt 
 */


data class PendingActionDecision (

    @Json(name = "action_id")
    val actionId: kotlin.String,

    @Json(name = "run_id")
    val runId: kotlin.String,

    @Json(name = "status")
    val status: PendingActionDecision.Status,

    @Json(name = "decision")
    val decision: PendingActionDecision.Decision,

    @Json(name = "selected_option_id")
    val selectedOptionId: kotlin.String? = null,

    @Json(name = "answer")
    val answer: kotlin.String? = null,

    @Json(name = "decided_at")
    val decidedAt: java.time.OffsetDateTime? = null

) {

    /**
     * 
     *
     * Values: approved,rejected
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "approved") approved("approved"),
        @Json(name = "rejected") rejected("rejected");
    }
    /**
     * 
     *
     * Values: accept,decline,answer
     */
    @JsonClass(generateAdapter = false)
    enum class Decision(val value: kotlin.String) {
        @Json(name = "accept") accept("accept"),
        @Json(name = "decline") decline("decline"),
        @Json(name = "answer") answer("answer");
    }

}

