/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.models

import io.ycvk.acorn.api.models.PendingActionOption

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param actionId 
 * @param runId 
 * @param threadId 
 * @param kind 
 * @param status 
 * @param title 
 * @param options 
 * @param createdAt 
 * @param payload 
 * @param body 
 * @param reason 
 * @param rule 
 */


data class PendingActionDetail (

    @Json(name = "action_id")
    val actionId: kotlin.String,

    @Json(name = "run_id")
    val runId: kotlin.String,

    @Json(name = "thread_id")
    val threadId: kotlin.String,

    @Json(name = "kind")
    val kind: PendingActionDetail.Kind,

    @Json(name = "status")
    val status: PendingActionDetail.Status,

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "options")
    val options: kotlin.collections.List<PendingActionOption>,

    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "payload")
    val payload: kotlin.collections.Map<kotlin.String, kotlin.Any>,

    @Json(name = "body")
    val body: kotlin.String? = null,

    @Json(name = "reason")
    val reason: kotlin.String? = null,

    @Json(name = "rule")
    val rule: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: elicitation,operator_question
     */
    @JsonClass(generateAdapter = false)
    enum class Kind(val value: kotlin.String) {
        @Json(name = "elicitation") elicitation("elicitation"),
        @Json(name = "operator_question") operator_question("operator_question");
    }
    /**
     * 
     *
     * Values: pending
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "pending") pending("pending");
    }

}

