/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param key Android notification key; limited to 256 UTF-8 bytes.
 * @param `package` 
 * @param app 
 * @param postedAt Notification time, at most five minutes ahead of the server.
 * @param title 
 * @param text 
 */


data class PhoneNotificationInput (

    /* Android notification key; limited to 256 UTF-8 bytes. */
    @Json(name = "key")
    val key: kotlin.String,

    @Json(name = "package")
    val `package`: kotlin.String,

    @Json(name = "app")
    val app: kotlin.String,

    /* Notification time, at most five minutes ahead of the server. */
    @Json(name = "posted_at")
    val postedAt: java.time.OffsetDateTime,

    @Json(name = "title")
    val title: kotlin.String? = "",

    @Json(name = "text")
    val text: kotlin.String? = ""

) {


}

