/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param scope 
 * @param provider 
 * @param status 
 * @param reason 
 * @param startupStatus 
 * @param authStatus 
 */


data class ProviderReadiness (

    @Json(name = "scope")
    val scope: kotlin.String,

    @Json(name = "provider")
    val provider: kotlin.String,

    @Json(name = "status")
    val status: ProviderReadiness.Status,

    @Json(name = "reason")
    val reason: kotlin.String? = null,

    @Json(name = "startup_status")
    val startupStatus: kotlin.String? = null,

    @Json(name = "auth_status")
    val authStatus: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: passed,failed,blocked
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "passed") passed("passed"),
        @Json(name = "failed") failed("failed"),
        @Json(name = "blocked") blocked("blocked");
    }

}

