/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param kind 
 * @param title 
 * @param changed 
 * @param verified 
 * @param risks 
 * @param detailRunId 
 */


data class ResultMessagePart (

    @Json(name = "kind")
    val kind: ResultMessagePart.Kind,

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "changed")
    val changed: kotlin.collections.List<kotlin.String>,

    @Json(name = "verified")
    val verified: kotlin.collections.List<kotlin.String>,

    @Json(name = "risks")
    val risks: kotlin.collections.List<kotlin.String>,

    @Json(name = "detail_run_id")
    val detailRunId: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: result
     */
    @JsonClass(generateAdapter = false)
    enum class Kind(val value: kotlin.String) {
        @Json(name = "result") result("result");
    }

}

