/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param threadId 
 * @param status 
 * @param mode 
 * @param createdAt 
 * @param completedAt 
 */


data class Run (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "thread_id")
    val threadId: kotlin.String,

    @Json(name = "status")
    val status: Run.Status,

    @Json(name = "mode")
    val mode: Run.Mode,

    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "completed_at")
    val completedAt: java.time.OffsetDateTime? = null

) {

    /**
     * 
     *
     * Values: running,completed,interrupted,failed
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "running") running("running"),
        @Json(name = "completed") completed("completed"),
        @Json(name = "interrupted") interrupted("interrupted"),
        @Json(name = "failed") failed("failed");
    }
    /**
     * 
     *
     * Values: direct,agent,plan_execute
     */
    @JsonClass(generateAdapter = false)
    enum class Mode(val value: kotlin.String) {
        @Json(name = "direct") direct("direct"),
        @Json(name = "agent") agent("agent"),
        @Json(name = "plan_execute") plan_execute("plan_execute");
    }

}

