/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param artifactId 
 * @param runId 
 * @param kind 
 * @param sizeBytes 
 * @param sha256 
 * @param createdAt 
 * @param sessionId 
 * @param sourceToolResultRef 
 * @param title 
 * @param mimeType 
 */


data class RunArtifact (

    @Json(name = "artifact_id")
    val artifactId: kotlin.String,

    @Json(name = "run_id")
    val runId: kotlin.String,

    @Json(name = "kind")
    val kind: RunArtifact.Kind,

    @Json(name = "size_bytes")
    val sizeBytes: kotlin.Long,

    @Json(name = "sha256")
    val sha256: kotlin.String,

    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "session_id")
    val sessionId: kotlin.String? = null,

    @Json(name = "source_tool_result_ref")
    val sourceToolResultRef: kotlin.String? = null,

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "mime_type")
    val mimeType: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: text,markdown,json,diff,log,test_report,binary
     */
    @JsonClass(generateAdapter = false)
    enum class Kind(val value: kotlin.String) {
        @Json(name = "text") text("text"),
        @Json(name = "markdown") markdown("markdown"),
        @Json(name = "json") json("json"),
        @Json(name = "diff") diff("diff"),
        @Json(name = "log") log("log"),
        @Json(name = "test_report") test_report("test_report"),
        @Json(name = "binary") binary("binary");
    }

}

