/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.models

import io.ycvk.acorn.api.models.Run
import io.ycvk.acorn.api.models.RunArtifact
import io.ycvk.acorn.api.models.RunEvent
import io.ycvk.acorn.api.models.Thread

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param run 
 * @param thread 
 * @param events 
 * @param artifacts 
 */


data class RunDetail (

    @Json(name = "run")
    val run: Run,

    @Json(name = "thread")
    val thread: Thread,

    @Json(name = "events")
    val events: kotlin.collections.List<RunEvent>,

    @Json(name = "artifacts")
    val artifacts: kotlin.collections.List<RunArtifact>

) {


}

