/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.models

import io.ycvk.acorn.api.models.RunEventPlannedToolCall

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param sequence 
 * @param role 
 * @param delta 
 * @param reasoning Model thinking/reasoning content for reasoning-capable models
 * @param messageId 
 * @param isFinal 
 * @param toolCalls 
 * @param meta 
 */


data class RunEventAssistantDelta (

    @Json(name = "sequence")
    val sequence: kotlin.Int,

    @Json(name = "role")
    val role: kotlin.String? = null,

    @Json(name = "delta")
    val delta: kotlin.String? = null,

    /* Model thinking/reasoning content for reasoning-capable models */
    @Json(name = "reasoning")
    val reasoning: kotlin.String? = null,

    @Json(name = "message_id")
    val messageId: kotlin.String? = null,

    @Json(name = "is_final")
    val isFinal: kotlin.Boolean? = null,

    @Json(name = "tool_calls")
    val toolCalls: kotlin.collections.List<RunEventPlannedToolCall>? = null,

    @Json(name = "meta")
    val meta: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

) {


}

