/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param kind 
 * @param actorIds 
 * @param toolNames 
 * @param paths 
 * @param reason 
 */


data class RunEventMessageWarningFact (

    @Json(name = "kind")
    val kind: RunEventMessageWarningFact.Kind? = null,

    @Json(name = "actor_ids")
    val actorIds: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "tool_names")
    val toolNames: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "paths")
    val paths: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "reason")
    val reason: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: file_collision,directory_overlap,unknown_scope
     */
    @JsonClass(generateAdapter = false)
    enum class Kind(val value: kotlin.String) {
        @Json(name = "file_collision") file_collision("file_collision"),
        @Json(name = "directory_overlap") directory_overlap("directory_overlap"),
        @Json(name = "unknown_scope") unknown_scope("unknown_scope");
    }

}

