/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.models

import io.ycvk.acorn.api.models.ClientAgentMessageEvent
import io.ycvk.acorn.api.models.ClientAssistantDeltaEvent
import io.ycvk.acorn.api.models.ClientDecisionBlockedEvent
import io.ycvk.acorn.api.models.ClientElicitationDecidedEvent
import io.ycvk.acorn.api.models.ClientElicitationPendingEvent
import io.ycvk.acorn.api.models.ClientOperatorQuestionDecidedEvent
import io.ycvk.acorn.api.models.ClientOperatorQuestionPendingEvent
import io.ycvk.acorn.api.models.ClientRunCompletedEvent
import io.ycvk.acorn.api.models.ClientRunFailedEvent
import io.ycvk.acorn.api.models.ClientRunInterruptedEvent
import io.ycvk.acorn.api.models.ClientRunResumeRequestedEvent
import io.ycvk.acorn.api.models.ClientRunStartedEvent
import io.ycvk.acorn.api.models.DecisionBlockedData

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param eventId 
 * @param runId 
 * @param seq 
 * @param ts 
 * @param type 
 * @param `data` 
 */


interface RunEvent {

    @Json(name = "event_id")
    val eventId: kotlin.String
    @Json(name = "run_id")
    val runId: kotlin.String
    @Json(name = "seq")
    val seq: kotlin.Long
    @Json(name = "ts")
    val ts: java.time.OffsetDateTime
    @Json(name = "type")
    val type: kotlin.Any?
    @Json(name = "data")
    val `data`: DecisionBlockedData

}

