/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.models

import io.ycvk.acorn.api.models.RunEventMessageWarningFact
import io.ycvk.acorn.api.models.RunEventPlannedToolCall

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param role 
 * @param content 
 * @param reasoning 
 * @param toolCalls 
 * @param warningFacts 
 * @param toolCallId 
 * @param toolName 
 * @param meta 
 */


data class RunEventMessage (

    @Json(name = "role")
    val role: kotlin.String? = null,

    @Json(name = "content")
    val content: kotlin.String? = null,

    @Json(name = "reasoning")
    val reasoning: kotlin.String? = null,

    @Json(name = "tool_calls")
    val toolCalls: kotlin.collections.List<RunEventPlannedToolCall>? = null,

    @Json(name = "warning_facts")
    val warningFacts: kotlin.collections.List<RunEventMessageWarningFact>? = null,

    @Json(name = "tool_call_id")
    val toolCallId: kotlin.String? = null,

    @Json(name = "tool_name")
    val toolName: kotlin.String? = null,

    @Json(name = "meta")
    val meta: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

) : kotlin.collections.HashMap<String, kotlin.Any>() {


}

