/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param runId 
 * @param threadId 
 * @param threadTitle 
 * @param status 
 * @param mode 
 * @param preview 
 * @param lastEventLabel 
 * @param attentionLevel 
 * @param durationMs 
 * @param createdAt 
 * @param updatedAt 
 */


data class RunSummary (

    @Json(name = "run_id")
    val runId: kotlin.String,

    @Json(name = "thread_id")
    val threadId: kotlin.String,

    @Json(name = "thread_title")
    val threadTitle: kotlin.String,

    @Json(name = "status")
    val status: RunSummary.Status,

    @Json(name = "mode")
    val mode: RunSummary.Mode,

    @Json(name = "preview")
    val preview: kotlin.String,

    @Json(name = "last_event_label")
    val lastEventLabel: kotlin.String,

    @Json(name = "attention_level")
    val attentionLevel: RunSummary.AttentionLevel,

    @Json(name = "duration_ms")
    val durationMs: kotlin.Long,

    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime

) {

    /**
     * 
     *
     * Values: running,completed,interrupted,failed
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "running") running("running"),
        @Json(name = "completed") completed("completed"),
        @Json(name = "interrupted") interrupted("interrupted"),
        @Json(name = "failed") failed("failed");
    }
    /**
     * 
     *
     * Values: direct,agent,plan_execute
     */
    @JsonClass(generateAdapter = false)
    enum class Mode(val value: kotlin.String) {
        @Json(name = "direct") direct("direct"),
        @Json(name = "agent") agent("agent"),
        @Json(name = "plan_execute") plan_execute("plan_execute");
    }
    /**
     * 
     *
     * Values: normal,needs_action,failed,running
     */
    @JsonClass(generateAdapter = false)
    enum class AttentionLevel(val value: kotlin.String) {
        @Json(name = "normal") normal("normal"),
        @Json(name = "needs_action") needs_action("needs_action"),
        @Json(name = "failed") failed("failed"),
        @Json(name = "running") running("running");
    }

}

