/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param tools 
 * @param toolsets 
 * @param bins 
 * @param env 
 */


data class SkillRequirements (

    @Json(name = "tools")
    val tools: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "toolsets")
    val toolsets: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "bins")
    val bins: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "env")
    val env: kotlin.collections.List<kotlin.String>? = null

) {


}

