/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.models

import io.ycvk.acorn.api.models.SkillRequirements

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param name 
 * @param version 
 * @param eligible 
 * @param category 
 * @param summary 
 * @param requirements 
 * @param disabledReasons 
 */


data class SkillSummary (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "version")
    val version: kotlin.String,

    @Json(name = "eligible")
    val eligible: kotlin.Boolean,

    @Json(name = "category")
    val category: kotlin.String? = null,

    @Json(name = "summary")
    val summary: kotlin.String? = null,

    @Json(name = "requirements")
    val requirements: SkillRequirements? = null,

    @Json(name = "disabled_reasons")
    val disabledReasons: kotlin.collections.List<kotlin.String>? = null

) {


}

