/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.models

import io.ycvk.acorn.api.models.CapabilitiesFeatures
import io.ycvk.acorn.api.models.CapabilitiesModel
import io.ycvk.acorn.api.models.CapabilitiesSummary
import io.ycvk.acorn.api.models.ProviderReadiness
import io.ycvk.acorn.api.models.RuntimeReadiness

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param runtimeReadiness 
 * @param model 
 * @param workspaceRoot 
 * @param summary 
 * @param features 
 * @param providerReadiness 
 */


data class SystemStatus (

    @Json(name = "runtime_readiness")
    val runtimeReadiness: RuntimeReadiness,

    @Json(name = "model")
    val model: CapabilitiesModel,

    @Json(name = "workspace_root")
    val workspaceRoot: kotlin.String,

    @Json(name = "summary")
    val summary: CapabilitiesSummary,

    @Json(name = "features")
    val features: CapabilitiesFeatures,

    @Json(name = "provider_readiness")
    val providerReadiness: kotlin.collections.List<ProviderReadiness>? = null

) {


}

