/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param title 
 * @param workspaceRoot 
 * @param createdAt 
 * @param updatedAt 
 * @param state 
 * @param latestRunId 
 */


data class Thread (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "workspace_root")
    val workspaceRoot: kotlin.String,

    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    @Json(name = "state")
    val state: Thread.State,

    @Json(name = "latest_run_id")
    val latestRunId: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: new,running,completed,failed,interrupted,degraded
     */
    @JsonClass(generateAdapter = false)
    enum class State(val value: kotlin.String) {
        @Json(name = "new") new("new"),
        @Json(name = "running") running("running"),
        @Json(name = "completed") completed("completed"),
        @Json(name = "failed") failed("failed"),
        @Json(name = "interrupted") interrupted("interrupted"),
        @Json(name = "degraded") degraded("degraded");
    }

}

