/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param actionId 
 * @param toolName 
 * @param arguments 
 * @param decision 
 */


data class ToolApprovalData (

    @Json(name = "action_id")
    val actionId: kotlin.String,

    @Json(name = "tool_name")
    val toolName: kotlin.String? = null,

    @Json(name = "arguments")
    val arguments: kotlin.String? = null,

    @Json(name = "decision")
    val decision: ToolApprovalData.Decision? = null

) {

    /**
     * 
     *
     * Values: accept,decline
     */
    @JsonClass(generateAdapter = false)
    enum class Decision(val value: kotlin.String) {
        @Json(name = "accept") accept("accept"),
        @Json(name = "decline") decline("decline");
    }

}

