/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.ycvk.acorn.api.models

import io.ycvk.acorn.api.models.MessageAction

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param kind 
 * @param status 
 * @param title 
 * @param summary 
 * @param detailRunId 
 * @param action 
 */


data class WorkStatusMessagePart (

    @Json(name = "kind")
    val kind: WorkStatusMessagePart.Kind,

    @Json(name = "status")
    val status: WorkStatusMessagePart.Status,

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "summary")
    val summary: kotlin.String,

    @Json(name = "detail_run_id")
    val detailRunId: kotlin.String? = null,

    @Json(name = "action")
    val action: MessageAction? = null

) {

    /**
     * 
     *
     * Values: work_status
     */
    @JsonClass(generateAdapter = false)
    enum class Kind(val value: kotlin.String) {
        @Json(name = "work_status") work_status("work_status");
    }
    /**
     * 
     *
     * Values: working,interrupted,failed
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "working") working("working"),
        @Json(name = "interrupted") interrupted("interrupted"),
        @Json(name = "failed") failed("failed");
    }

}

